### ISSUE TITLE
Benchmark test for FPC (lazarus-delphi) servers with mormot and brook frameworks against node and python (flask).

### ISSUE THREAD

**Issue by ibelarouci** [synopse/mORMot2#113]
Benchmark test for FPC (lazarus-delphi) servers with mormot and brook frameworks against node and python (flask).

[link github](https://github.com/ibelarouci/nodpyvsfpcserver)

We can see the test result of each http server and how mormot wins the challenge, fpc mormot is 3 times faster than node and 2 times faster than fpc Brook, however http server with python is the slowest based on the result. please contact me with any suggestions to improve any of the servers and thank you. email: i.belarouci@gmail.com.

**Comment by synopse** [comment]
Interesting feedback!
Thanks!

But perhaps worth a discussion on our forum instead of a issue on github?
Since there is no performance issue I guess here. ;)
https://synopse.info/forum

**Comment by synopse** [comment]
Brook is in fact using the https://risoflora.github.io/libsagui/ for its HTTP layer.
So it is not even a full pascal framework, as mORMot is.

**Comment by ibelarouci** [comment]
Forgive me for that, yes there is no issue , but your beautiful work it
make me proud to use it , excellent job and thank you, thank you.
