### ISSUE TITLE
TZipWrite.AddDeflate() and MODERN 7FM.exe

### ISSUE THREAD

**Issue by vlad-mal** [synopse/mORMot2#115]
Hello!
I found that .zip files created with a call to the **AddDeflated**() method:
    procedure AddDeflated(const aFileName: TFileName;
      RemovePath: boolean = true; CompressLevel: integer = 6;
      ZipName:TFileName=''); overload;
- are handled incorrectly by modern versions of the graphical utility 7zFM.exe (7zip file manager ) when the ZipName string-parameter contains "reverse" eg "Delphi2007\Trash\1zip64". In this case, all files appear as being in the same directory, with a long file name that includes the directory.
For example, let's create a directory containing
1. file named "File In Root Folder.txt"
2. directory named "Child Folder"
3. In the "Child Folder" directory, create a file named "File in Child Folder.txt".
 
Now let's zip this directory by sequentially calling the AddDeflate method for each file. The ZipName must contain a relative path with backslashes. Then we open the resulting archive (necessarily with a NEW version) with the 7zFM utility. We see that there is no file structure in the archive, there are only a couple of files with strange names:

![1](https://user-images.githubusercontent.com/2589195/183150564-e09145a1-fdf6-4457-a954-5839f9f29b6c.png)

If you change the backslashes to forward slashes, then everything will be fine:
![2](https://user-images.githubusercontent.com/2589195/183150621-95fcd8a6-add2-4313-a072-52740b1a3f4c.png)
...
Note: if you create a .zip file not one at a time, but all at once, by calling the AddFolder() method, then everything will be fine: in the implementation of the AddFolder() method, the AddDeflated() method is called, in which only forward slashes are present!
Regards, Malinovsky Vladimir.

**Comment by synopse** [comment]
I am not to reproduce your problem.
Do you have some code to share to reproduce it?

TZipWrite.AddDeflated() calls ZipName := NormalizeZipName(aFileName) in line 1745 which should put the proper / separator everywhere in place to \.

**Comment by synopse** [comment]
I tried to make a paranoid fix for this issue.
