### ISSUE TITLE
Access violations when using TSynLog + sllError

### ISSUE THREAD

**Issue by salvadorbs** [synopse/mORMot2#117]
Hi,

I use the mormot logger and I noticed that when an error is logged (TSynLog.Add.Log (sllError, 'TESTING');), the program receives an access violations and crashes. Last good commit is 261554b86b91d57943d3a0e6a4ed11b5ef58ed6d, but I see that there have been several changes and I cannot help further in the analysis.

I leave you attached a simple project to test.[sample_log.zip](https://github.com/synopse/mORMot2/files/9445504/sample_log.zip)

Other infos:
![image](https://user-images.githubusercontent.com/3731721/187228677-43c7efb9-5667-41f1-a1c3-b643b4f8c280.png)

Do you have any suggestions for me to solve the problem?

**Comment by synopse** [comment]
Which debug format did you use?

You should use Dwarf 2 or 3.

**Comment by synopse** [comment]
I am not able to reproduce your issue on Win32 or Win64 with Dwarf 2 debug symbols, and the current version of mORMot.

**Comment by salvadorbs** [comment]
![image](https://user-images.githubusercontent.com/3731721/187860137-ca875554-5d0d-43f5-9897-fb84097c9fb9.png)

Retried with last mORMot sources. 
![image](https://user-images.githubusercontent.com/3731721/187860235-25b7defe-1d80-48b6-ab1f-3b3ae01c6b44.png)

**Comment by synopse** [comment]
I am not able to reproduce.

Try to debug more on your side.
What is the stack trace?
Where is the exact location?

**Comment by salvadorbs** [comment]
Tried without LCL UI and it works. So somewhere LCL introduces something the debug parser doesn't like.

[Stack trace](https://gist.github.com/salvadorbs/2f7260b2905c453bc6233e4759904c55)

**Comment by synopse** [comment]
Can you debug in -O0 or -O1 level to have a more precise stack trace?

**Comment by salvadorbs** [comment]
With Dwarf3, -O0 and fpdebug backend, I can't debug in TDwarfReader.ParseCompilationUnits. With gdb, I can step to step in this function, but I can't watch any variables. The issue seems in files[prevfile], but I can't see for which unit.
https://github.com/synopse/mORMot2/blob/9aba441c732bf63546b21e9e6ab46cd71e0d6a29/src/core/mormot.core.log.pas#L2501

Anyway in this if https://github.com/synopse/mORMot2/blob/9aba441c732bf63546b21e9e6ab46cd71e0d6a29/src/core/mormot.core.log.pas#L2484 I added another condition `and (prevfile <= (length(files) - 1)` and it works without exception. Can you please check it? Thanks

**Comment by synopse** [comment]
That is very informative information!

Please try https://github.com/synopse/mORMot2/commit/c21ee776

**Comment by salvadorbs** [comment]
It works! Thank you very much!
