### ISSUE TITLE
Access violations on ToDataset using mORMot2-2.0.4148

### ISSUE THREAD

**Issue by ThepSamart** [synopse/mORMot2#123]
I got access violation using latest release mORMot2-2.0.4148.
code:
// Return result with autoFree object for Transport rowset
  TAutoFree.One(s_data, ToDataSet(nil, i_rows));
  aTable.LoadFromDataSetWithStructure(s_data);

An exception are in TSqlDBProxyStatementRandomAccess.Create() and TSqlDBStatementWithParamsAndColumns.Create(). 
TSqlDBProxyStatementRandomAccess.Create() passed aConnection as nil to TSqlDBStatementWithParamsAndColumns.Create(), so testing for aConnection will raise error.

This is not occured in previous release mORMot2-2.0.3780.
![Screenshot 2022-10-18 175730](https://user-images.githubusercontent.com/116090219/196450679-11b2749d-d093-4564-82cf-8b9d7c67e237.png)

**Comment by synopse** [comment]
Please use the forum and provide a [minimal reproducible example ](https://stackoverflow.com/help/minimal-reproducible-example) as external git.

**Comment by synopse** [comment]
Thanks for your discussion on https://synopse.info/forum/viewtopic.php?id=6384

The culprit is clearly https://github.com/synopse/mORMot2/commit/cb178e5c9638a467a80830edaf3fd220cd7a5c62

Should be fixed now.
