### ISSUE TITLE
Version ? Lazarus 2.1.0-r64940

### ISSUE THREAD

**Issue by kremlacek** [synopse/mORMot2#129]
Mormot2/readme:
Is currently validated against FPC 3.2.0-r45643 (Lazarus 2.1.0-r64940), Delphi 7, 2007, 2010, XE4, XE7 and 10.4;
??? (Lazarus **2.1.0**-r64940) or (Lazarus **2.0.10**-...)

**Comment by synopse** [comment]
From the Lazarus About Box:
Lazarus 2.1.0 r64940 FPC 3.2.0 x86_64-linux-gtk2

From the FPC command line:
Free Pascal Compiler version 3.2.0-r45643 [2021/05/21] for x86_64

**Comment by kremlacek** [comment]
And where is the version Lazarus 2.1.0 to download?
![image](https://user-images.githubusercontent.com/23012626/204086748-0900a186-ab73-4195-b6c6-9041b8c34b35.png)

**Comment by synopse** [comment]
Use fpcupdeluxe to build it.

Or just download the latest Lazarus stable version, which is 2.2.4 IIRC.
It will work with mORMot.

The idea with the version we state is that it is the one we use.
It does not mean that it is the only one supported.
