### ISSUE TITLE
TSynLogFile ExeVersion

### ISSUE THREAD

**Issue by GoranDespalatovic** [synopse/mORMot2#136]
I've noticed strange behaviour of LogView with recently generated log files. I've found that exe version is missing from log file header.
TSynLogFile.LoadFromMap expects ExeVersion even if exe does not have VersionInfo linked.

So I think this
```
procedure ComputeExecutableHash;
begin
  with Executable do
  begin
    if Version.Version32 = 0 then  
      _fmt('%s (%s)', [ProgramFileName,
        Version.BuildDateTimeString], ProgramFullSpec)
    else
      _fmt('%s %s (%s)', [ProgramFileName,
        Version.Detailed, Version.BuildDateTimeString], ProgramFullSpec);
```
should be replaced with
```
procedure ComputeExecutableHash;
begin
  with Executable do
  begin
    if Version.Version32 = 0 then  
      _fmt('%s 0.0.0.0 (%s)', [ProgramFileName,
        Version.BuildDateTimeString], ProgramFullSpec)
    else
      _fmt('%s %s (%s)', [ProgramFileName,
        Version.Detailed, Version.BuildDateTimeString], ProgramFullSpec);
```

to avoid TSynLogFile.LoadFromMap to fail halfway (when it cannot get exe version)

**Comment by synopse** [comment]
You are right.
I just fixed it in LogView using https://github.com/synopse/mORMot/commit/54bf242065162e677ddebbf1a97b51231168e3d6

But perhaps that your solution is better.

**Comment by synopse** [comment]
I have committed https://github.com/synopse/mORMot2/commit/2926b7e0#diff-0987cc3e889c47c5c2de7ea1038410cb96158781a4f5e3398c7a59974bfac968L6902
Which may help without touching the LogView tool itself.

**Comment by synopse** [comment]
Closed due to no reaction after the commit.

Please reopen if needed.
