### ISSUE TITLE
Memory leak in mormot.rest.client TRestClientUri.InternalNotificationMethodExecute

### ISSUE THREAD

**Issue by GoranDespalatovic** [synopse/mORMot2#137]
When using ServiceNotificationMethodViaMessages I've got memory leak with instance ofTRestClientUriServiceNotification hanging.

In procedure TRestClientUri.InternalNotificationMethodExecute
sub-procedure  procedure Call(methodIndex: integer; const par: RawUtf8; res: TJsonWriter);
execmsg variable is not freed, so I think it should be :
```
...
      execmsg := TRestClientUriServiceNotification.Create(
        callback.Factory, method, []);
      try                                                         // gigo
        execmsg.fOwner := self;
        execmsg.fInstance := callback.Instance;
        execmsg.fPar := par;
        with fServiceNotificationMethodViaMessages do
          ok := PostMessage(Wnd, Msg, Wnd, PtrInt(execmsg));
        if ok then
          exit;
      finally                                                     // gigo
        execmsg.Free;                                             // gigo
      end;                                                        // gigo
...
```

**Comment by synopse** [comment]
I don't think so: execmsg is passed as a pointer to POstMessage() and is to be released by the message handler itself in TRestClientUri.ServiceNotificationMethodExecute.
