### ISSUE TITLE
WebSocket CloseConnection DeadLock

### ISSUE THREAD

**Issue by Coldzer0** [synopse/mORMot2#142]
I'm using the latest version 412fd88377921862819cd955a5cdfd9c08e39c6d  - mormot.commit.inc = `2.0.4828`
I was testing my web socket server, enabled some custom logs to keep track of any errors, and noticed that no activities were happening on the server logs.

So I was trying to interact with one of the connections. But the GUI freezes, and I got this stack trace.

![image](https://i.imgur.com/19F7tqK.png)

I tried to reproduce it but couldn't, as I was testing with many connections.

**Comment by Coldzer0** [comment]
I got this one too

![image](https://user-images.githubusercontent.com/6647006/216749097-f4d38aaa-66f8-45eb-88b2-bb655e933ab7.png)

**Comment by Coldzer0** [comment]
So I was trying to take a log that shows what happened before I tried to close and free the server.

First, here's a log with trace enabled.

[IOServerLogs 20230204 093602.zip](https://github.com/synopse/mORMot2/files/10609379/IOServerLogs.20230204.093602.zip)


You will notice that at the end of the log file, there are a lot of
```
20230204 17433752  1 trace mormot.net.async.TPollConnectionSockets(01b11b4c6ad0) PollForPendingEvents=4 in fPoll[0] (subscribed=4) pending=4 29us
20230204 17433753  1 trace mormot.net.async.TPollConnectionSockets(01b11b4c6ad0) PollForPendingEvents=4 in fPoll[0] (subscribed=4) pending=0 40us
20230204 17433753  1 trace mormot.net.async.TPollConnectionSockets(01b11b4c6ad0) PollForPendingEvents=4 in fPoll[0] (subscribed=4) pending=4 32us
20230204 17433753  1 trace mormot.net.async.TPollConnectionSockets(01b11b4c6ad0) PollForPendingEvents=4 in fPoll[0] (subscribed=4) pending=4 26us
20230204 17433753  1 trace mormot.net.async.TPollConnectionSockets(01b11b4c6ad0) PollForPendingEvents=4 in fPoll[0] (subscribed=4) pending=4 28us
```




And then, when I tried to close the server, it hung, and EurekaLog gave me this report.

![image](https://user-images.githubusercontent.com/6647006/216784119-aeb7c415-3d69-42f3-9c41-36bdcf5d2bc9.png)



And at one time, while I was testing, I got this. 
```
Application made attempt to call method of already deleted object: $000001E30C501990 OBJECT [?] 0 bytes

Call Stack:

[000000000143D870] mormot.net.async.TPollAsyncSockets.CloseConnection (Line 1399, "mormot.net.async.pas")
[000000000143D679] mormot.net.async.TPollAsyncSockets.UnlockAndCloseConnection (Line 1359, "mormot.net.async.pas")
[000000000143DD11] mormot.net.async.TPollAsyncSockets.ProcessRead (Line 1499, "mormot.net.async.pas")
[000000000143F3BB] mormot.net.async.TAsyncConnectionsThread.Execute (Line 1857, "mormot.net.async.pas")
[0000000000A05670] System.Classes.ThreadProc
[00007FFA1BBF7ACE] KERNEL32.BaseThreadInitThunk
[000000000143EE94] mormot.net.async.TAsyncConnectionsThread.Create (Line 1739, "mormot.net.async.pas")
```

There's a problem in the Poll events loop; when it happens, the server can't receive or send any data.
I'm still trying to figure out why the `PollForPendingEvents` kept looping and didn't break out of the loop.

That's all I've for now, I hope it will help identify the problem.

**Comment by synopse** [comment]
Did you try with the very latest source?

I guess your problem could already be fixed by https://github.com/synopse/mORMot2/commit/c5326052b7ad31ccd33a3f604ef5d8133923e9e1

**Comment by Coldzer0** [comment]
> I am not sure EurekaLog is compatible with mORMot exception interception of TSynLog.

I'll use `NOEXCEPTIONINTERCEPT` on my build and test again.

But the exceptions shown above are because the main thread hung on ReadOnlyLockSpin.
I have EurekaLog options set to if after 120 sec the main thread is feezed, it will report.

**Comment by synopse** [comment]
I will investigate. It seems to affect only Windows / TPollConnectionSockets.

**Comment by synopse** [comment]
Please try with the latest commit above.

I was not able to reproduce the issue here.
Even with https://github.com/synopse/mORMot2/commit/cd0cf96a to have something similar to your issue.

**Comment by Coldzer0** [comment]
Hello @synopse 

I'm still testing, But here's the result so far.

I left the server running the last night, and everything is working without a problem.
I tried to close and open the server from the GUI ( shutting down and freeing the server object ).
```
Server.Shutdown; // to enable fShutdownInProgress
FreeAndNilSafe(Server);
```

The server has 250 to 300 concurrent connections
I'll keep testing and updating you here.

**Comment by Coldzer0** [comment]
Hello @synopse 

Btw I found out that there was a bug in my code that I did use `Self.Settings.SetDefaults` after Create, and this makes the `HeartbeatDelay = 0`

So After Fixing this bug and two days of testing, `everything is working without a problem`

And I notice something regarding the `TWebSocketAsyncServer` The first thread always uses the most CPU, around 3% to 5%. 
Even when I use `hsoThreadSmooting` still, all other threads are in an idle state waiting.

I've around (300+-) Concurrent connections using WebSocket and sending data almost every couple of seconds.
Do you have any recommendations for this situation?

**Comment by synopse** [comment]
Nice to know that everything is working now without a problem!

About the thread usage, `hsoThreadSmooting` should leverage the threads in order.
The threads won't be used to maintain the connections - even if they are thousands of them.
Only when there is a request, a thread will be awaken, starting from the first one of the pool. So if you have only little traffic, then only the first thread of the pool would be used, which is enough and better for scaling.
Use a more aggressive tool like `wrk`  to see some over threads working.

**Comment by synopse** [comment]
So, if it is resolved, I guess you can close the Issue now. ;)

**Comment by Coldzer0** [comment]
Thanks for the clarification, It's solved now.

Again Thanks for your excellent work.
