### ISSUE TITLE
RecordVersionSynchroniseSlave doesn't work as expected

### ISSUE THREAD

**Issue by avavdoshin** [synopse/mORMot2#143]
RecordVersionSynchroniseSlave called from slave server doesn't work as expected and described in documentation.
F.e., i have 4 TOrms (consts, dict, params, paramhistory) each with Version: TRecordVersion published fields.
I created few instances of this orms in mixed order, f.e. dict - params - paramhistory - consts, so because of monotonic of TRecordVersion, attribute Version for this instances will be (for example): 
Consts: 4
Dict: 1
Params: 2
ParamHistory: 3

If i'll try ty call RecordVersionSynchroniseSlave for each orms one-by-one (from Consts to ParamHistory) it will stop synchronise at consts (because it calculates maximum record version from ALL tables, not from one i synchronise).

**Comment by synopse** [comment]
Please try with the latest commit.

It will now maintain one TRecordVersion per table - so it should fix your issue.

**Comment by avavdoshin** [comment]
Works now, thank you!
