### ISSUE TITLE
test.net.proto.pas test case error for DNToCN

### ISSUE THREAD

**Issue by PierceNg** [synopse/mORMot2#151]
Hi Arnaud,

I built and ran ```mormot2tests```. It gave two assertion failures, in lines 356-360 of ```test.net.proto.pas```, in the ```DNToCN``` calls. Looking at the source of ```DNToCN``` from line 1068 of ```mormot.net.ldap```, it seems the assertions themselves are wrong. I changed them to following (swapped the order of OU when rendered as CN) and the tests pass:

```
  CheckEqual(DNToCN('CN=User1,OU=Users,OU=London,DC=xyz,DC=local'),
    'xyz.local/London/Users/User1');
  CheckEqual(DNToCN(
    'cn=JDoe,ou=Widgets,ou=Manufacturing,dc=USRegion,dc=OrgName,dc=com'),
    'USRegion.OrgName.com/Manufacturing/Widgets/JDoe');
```

And the tests...

```
Using mORMot 2.0.4952
    TSqlite3LibraryStatic 3.40.0 with internal MM
Generated with: Free Pascal 3.3.1 64 bit Linux compiler

Time elapsed for all tests: 2m00
Performed 2023-03-02 20:48:30 by pierce on Linben

Total assertions failed for all test suits:  0 / 75,972,464
! All tests passed successfully.
```

Almost 76 million assertions. Awesome!

**Comment by synopse** [comment]
It has been fixed in-between.

Thanks for the report
