### ISSUE TITLE
Exceptions in "mormot2tests"

### ISSUE THREAD

**Issue by kremlacek** [synopse/mORMot2#157]
What is the cause? (clean installation Lazarus 2.2.2, Lazarus 2.2.4, Lazarus 2.2.6 on Windows 10 Czech language - CP-1250)

![image](https://user-images.githubusercontent.com/23012626/224058809-a1901e38-53e8-4e36-9fde-a055491d6c85.png)

Thanks for any help

**Comment by synopse** [comment]
Which FPC revision?

**Comment by kremlacek** [comment]
From about:
Lazarus 2.2.6 (rev lazarus_2_2_6) FPC 3.2.2 x86_64-win64-win32/win64

**Comment by synopse** [comment]
We are not able to reproduce the problem.

On which test source code lines does the exception raise?
