### ISSUE TITLE
Memory leak in a simple situation

### ISSUE THREAD

**Issue by ptvoinfo** [synopse/mORMot2#170]
I would like to report a small problem:

Latest mormot.core.fpcx64mm.

GetMem(p, 0);
FreeMem(p, 0); 

Yes, this allocation looks strange, but the memory manager reports about a small memory block leak.

I've found a note in the code "we always need to allocate something", but _FreeMemSize does not free a block with the zero size.

**Comment by synopse** [comment]
You are right.
Even if Freemem(p,size) is almost never called in practice.

Should be fixed now.
