### ISSUE TITLE
mORMot2-2.0.stable\ex\mvc-blog\MVCServer.dpr compilation error on Lazarus

### ISSUE THREAD

**Issue by thierrybo** [synopse/mORMot2#174]
Sorry if this is a stupid ticket, just discover Mormot.

in mvc-blog\MVCServer.dpr I have to replace line 8 :

```
{$ifdef OSWINDOWS}
  {$apptype console}
  {$R mormot.win.default.manifest.res}
{$endif OSWINDOWS} 
```   

with:

```
{$ifdef OSWINDOWS}
  {$apptype console}
  {$ifndef FPC}{$R mormot.win.default.manifest.res}{$endif FPC}
{$endif OSWINDOWS}   
``` 

otherwise I get 👍 

`MVCServer.dpr(85,1) Error: Can't open resource file "E:\Users\windows10\Documents\Lazarus\Composants\mORMot2-2.0.stable\ex\mvc-blog\mormot.win.default.manifest.res"`

**Comment by synopse** [comment]
Did you install the package?

**Comment by thierrybo** [comment]
Yes. and the mormot2test.lpi runs without any error.

By the way this was on my work computer. This evening I installed mormot2 on my personal computer and I get the same result :

https://i.imgur.com/38yrusY.png
