### ISSUE TITLE
mormot.ui.controls.THintWindowsDelayed.Paint  exception !!

### ISSUE THREAD

**Issue by aditeo** [synopse/mORMot2#177]
When i put mouse over column title on a TDrawgrid I get an memory exception.
The problem is happen on function DrawTextUtf8(...) when Text = ''

You can solve this problem by modify in file mormot.core.unicode.pas function Utf8DecodeToUnicode(..)
You need to initialize temp parameter when text = '' like this

function Utf8DecodeToUnicode(Text: PUtf8Char; Len: PtrInt; var temp: TSynTempBuffer): PtrInt;
begin
  if (Text = nil) or
     (Len <= 0) then
  begin
    temp.Init(0);           // <<-----   my solve to the problem
    result := 0;
  end
  else
  begin
    temp.Init(Len * 3); // maximum posible unicode size (if all <#128)
    result := Utf8ToWideChar(temp.buf, Text, Len) shr 1;
  end;
end;

**Comment by aditeo** [comment]
Way i see wrong text on the hint ?

![Screenshot 2023-04-19 080013](https://user-images.githubusercontent.com/62603945/232971286-0bb68118-ab72-4846-b2be-6a5a5f3957b9.png)
![Screenshot 2023-04-19 075905](https://user-images.githubusercontent.com/62603945/232971293-db2a5ae4-534c-4bb7-acdf-e5633817975f.png)

**Comment by synopse** [comment]
Should be fixed now.

Thanks for the report.

**Comment by aditeo** [comment]
On function that I modify upper you write
