### ISSUE TITLE
Exception triggered on new command-line parser

### ISSUE THREAD

**Issue by flydev-fr** [synopse/mORMot2#183]
I have been playing with the [new command-line parser](https://blog.synopse.info/?post/2023/04/19/New-Command-Line-Parser-in-mORMot-2) and when only the switch symbol is given as argument, an access violation is triggered, on Delphi and FPC.

#### Issue
```
$: Project1.exe /
EAccessViolation: Access violation
```
#### Expecting
```
Project1.exe / 
Unexpected / option

Usage: Project1 [options]
...
```

You can find a Delphi and FPC reproducible sample there:  [flydev-fr/mormot2-command-line-parser](https://github.com/flydev-fr/mormot2-command-line-parser)

Also just sent a PR #182

**Comment by synopse** [comment]
Perhaps linked to https://github.com/synopse/mORMot2/commit/38f27f08
