### ISSUE TITLE
mormot.ui.report.pas error in uses?

### ISSUE THREAD

**Issue by kremlacek** [synopse/mORMot2#187]
Unit mormot.ui.report.pas have not in uses mormot.core.os 
([dcc32 Error] mormot.ui.report.pas(5353): E2003 Undeclared identifier: 'ValidHandle')

**Comment by synopse** [comment]
On which compiler and revision?

ValidHandle() part of mormot.core.os IIRC.

Please use the forum to report this.

**Comment by synopse** [comment]
I guess I have found a problem.

Please try with this latest commit.
