### ISSUE TITLE
D7 compile mormot.db.rad.unidac.pas error

### ISSUE THREAD

**Issue by daselang** [synopse/mORMot2#188]
const
  /// UniDAC provider names corresponding to mormot.db.sql recognized SQL engines
  UNIDAC_PROVIDER: array[dOracle..high(TSqlDBDefinition)] of RawUtf8 = (
    'Oracle', 'SQL Server', 'Access', 'MySQL', 'SQLite', 'InterBase', 
    'NexusDB', 'PostgreSQL', 'DB2', '');

[Error] mormot.db.rad.unidac.pas(171): Number of elements differs from declaration.

I checked,
    dInformix,
    dMariaDB names are missing in the arrary.
 currently the dInformix is mapping to '',but dMariaDB is mapping to None.

**Comment by daselang** [comment]
@synopse  hi,why is the dINformix setted as '' in the latest update?

and 'MySQL' seems duplicated?
  UNIDAC_PROVIDER: array[dOracle..high(TSqlDBDefinition)] of RawUtf8 = (
    'Oracle', 'SQL Server', 'Access', 'MySQL', 'SQLite', 'InterBase', 
    'NexusDB', 'PostgreSQL', 'DB2', '', 'MySQL');

**Comment by synopse** [comment]
Perhaps because Informix is not supported by UniDac?
