### ISSUE TITLE
Example MongoDB not work for old CPU. Alternative

### ISSUE THREAD

**Issue by manlug** [synopse/mORMot2#190]
Hi,
example **mondgodb** not work, because docker with last version not run with old CPU.
[https://github.com/docker-library/mongo/issues/619](https://github.com/docker-library/mongo/issues/619)

Solved is force version 4.8.11, not necessary last version for a example
`sudo docker run --name mongodb -d -p 27017:27017 mongo:4.8.11`

**Comment by synopse** [comment]
I don't understand what 'not run with old CPU' mean.

**Comment by synopse** [comment]
So you mean that we need to change the comment about docker?
