### ISSUE TITLE
Example MongoDB not work in Lazarus (Linux)

### ISSUE THREAD

**Issue by manlug** [synopse/mORMot2#191]
**Version:**
Ubuntu 22.04.2 LTS (64bits)
Linux mordor 5.15.0-72-generic #79-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
Lazarus 2.2.6 (rev Unversioned directory) FPC 3.2.2 x86_64-linux-gtk2

**Compile Error:**
MongoDBTestCases.pas(71,12) Error: Identifier not found "TSQLRawBlob"
MongoDBTestCases.pas(71,23) Error: Error in type definition

Solved:
Replace TSQLRawBlob for RawBlob
Reference: [https://github.com/synopse/mORMot2/tree/master/src](https://github.com/synopse/mORMot2/tree/master/src)

**Comment by synopse** [comment]
It is because you enabled PUREMORMOT2 conditional, which was not supported by this sample.
