### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by hafedh-trimeche** [synopse/mORMot2#197]
Hello,

Please note this error message:
`[dcc64 Error] mormot.ui.pdf.pas(4858): E2003 Undeclared identifier: 'c'`

c variable should be declared:
```
function TPdfWrite.AddEscapeName(Text: PAnsiChar): TPdfWrite;
var
  c : Byte;

```
Best regards.

**Comment by synopse** [comment]
Should be fixed by https://github.com/synopse/mORMot2/commit/58e49cd3

Thanks for the report.

**Comment by synopse** [comment]
No update - I guess we could close the issue.
Please reopen it if needed.
