### ISSUE TITLE
Some of the Mormot Regression Tests fail on Odroid-X2 (ARM-v7) single board computer.

### ISSUE THREAD

**Issue by turkerali** [synopse/mORMot2#199]
Hi Arnaud,

First of all, thanks for your time and effort for this great library.

This will probably be a low-priority issue for you, but let me report it anyway.
I am using Odroid-X2 (ARM-v7) single board computer for development.
Today I downloaded the latest mormot 2 code (58e49cd) via fpcupdeluxe and ran the regression tests.
I got one exception (Bus error or misaligned data access) and 12 failures.
I am running the latest LTS Linux kernel (6.1.33) as of today. Let me know if you need more info.
Here is the full regression test log:
[mormot_error.txt](https://github.com/synopse/mORMot2/files/11718889/mormot_error.txt)
Here is error message from dmesg:
[ 2811.281608] 8<--- cut here ---
[ 2811.284085] Unhandled fault: external abort on non-linefetch (0x018) at 0xb64e0000
[ 2811.288996] [b64e0000] *pgd=b55d1831

Regards
Ali Erturk TURKER

**Comment by synopse** [comment]
There should be a .log file with some information about the exceptions.
Please enable debug information (as DWARF 2 or 3) and check the stack trace.

About the EBusError issue, I don't know exactly what is wrong. 
The memory leak comes from GetRawSmbiosFromMem - which is likely to be faulty.
We could need the stack trace on the exception from the logs.

My first guess is that there is trouble getting the reference JSON files used by Mustache, and that DNS tests fail also from a network issue.
You should be properly connected to the Internet to let the tests pass.

**Comment by turkerali** [comment]
Hi Arnaud

Thanks for your quick response and you're 100% right. After connecting to internet, I ran the regression test again, and the 12 failures are gone ( log: [mormot_error_rev01.txt](https://github.com/synopse/mORMot2/files/11720231/mormot_error_rev01.txt) )

As for the EBusError exception, there is no "/sys/firmware/dmi/tables/smbios_entry_point" file in the system. That may be x86 specific as you noted.

As a sidenote, I watch mormot2 rise in the techempower benchmarks with great pleasure. As you may remember our previous [conversation](https://github.com/synopse/mORMot2/issues/81), I was not happy with mormot2 async server performance and had switched to actix. Now mormot2 is better than actix in [composite scores](https://www.techempower.com/benchmarks/#section=test&runid=f968b601-cb68-4b85-8fdc-7ef9c22175b7&test=composite), so I think it is time to switch back to mormot :-)

Best regards,
Ali Erturk TURKER

**Comment by turkerali** [comment]
Hi Arnaud,

Today I downloaded a fresh copy ([1e1fe2d](https://github.com/synopse/mORMot2/commit/1e1fe2db156e566c0f49b0a94643c605f8f12369)) of mORMot2 with your updates and all the
smbios related error messages are gone in the regression test: ([mormot2_test_lazarus_odroid-x2_linux_rev02.txt](https://github.com/synopse/mORMot2/files/11730789/mormot2_test_lazarus_odroid-x2_linux_rev02.txt)).
Thanks a lot.

Interestingly, some JSON related tests were skipped. It just says:

`  - JSON benchmark: no assertion  144us`

However yesterday I got this output from the same regression test:

```
  - JSON benchmark: 100,519 assertions passed  26.90s
     StrLen() in 23.20ms, 844.9 MB/s
     IsValidUtf8(RawUtf8) in 89.19ms, 219.7 MB/s
     IsValidUtf8(PUtf8Char) in 102.64ms, 190.9 MB/s
     IsValidJson(RawUtf8) in 151.68ms, 129.2 MB/s
     IsValidJson(PUtf8Char) in 151.26ms, 129.6 MB/s
     JsonArrayCount(P) in 151.26ms i.e. 1M/s, 129.6 MB/s
     JsonArrayCount(P,PMax) in 151.91ms i.e. 1M/s, 129 MB/s
     JsonObjectPropCount() in 93.32ms, 121.6 MB/s
     jsonUnquotedPropNameCompact in 488.09ms, 35.6 MB/s
     jsonHumanReadable in 873.16ms, 28.5 MB/s
     TDocVariant in 4.17s i.e. 38.5K/s, 4.7 MB/s
     TDocVariant no guess in 5.03s i.e. 31.9K/s, 3.9 MB/s
     TDocVariant dvoIntern in 2.65s i.e. 60.5K/s, 7.3 MB/s
     TOrmTableJson save in 156.23ms i.e. 1M/s, 55.1 MB/s
     TOrmTableJson exp in 291.53ms i.e. 551.1K/s, 67.2 MB/s
     TOrmTableJson not exp in 121.70ms i.e. 1.2M/s, 70.8 MB/s
     TDocVariant FromResults exp in 1.85s i.e. 86.4K/s, 10.5 MB/s
     TDocVariant FromResults not exp in 1.73s i.e. 92.7K/s, 4.9 MB/s
     DynArrayLoadJson exp in 1.28s i.e. 125.4K/s, 15.3 MB/s
     DynArrayLoadJson non exp in 1.16s i.e. 137.7K/s, 7.3 MB/s
     TOrmPeopleObjArray exp in 2.38s i.e. 67.4K/s, 8.2 MB/s
     TOrmPeopleObjArray non exp in 1.63s i.e. 98.2K/s, 5.2 MB/s
     fpjson in 1.62s i.e. 9.8K/s, 1.2 MB/s
```

I did not touch anything, what might be the reason?

Regards,
Ali Erturk TURKER

**Comment by synopse** [comment]
Some of the JSON tests are using the big JSON content generated during ORM tests (file `test.json`).
So we need to run the tests twice to have a full coverage.

**Comment by turkerali** [comment]
Hi Arnaud,

Thanks for the explanation. mORMot2 is a huge leap over mORMot1, and I'm looking forward to see it on top of the web framework benchmarks.

Regards,
Ali Erturk TURKER
