### ISSUE TITLE
Allow HTTP compression for JSON:API media type "application/vnd.api+json"

### ISSUE THREAD

**Issue by rganz** [synopse/mORMot2#203]
[JSON:API](https://github.com/json-api/json-api) is a specification for REST/JSON and they [registered the media type at IANA](https://jsonapi.org/#mime-types).

In mormot.net.http there is a whitelist which media types can be compressed or not. It can be bypassed by registering compression with aCompressMinSize = 0, but then we lose the ability to skip compression for small content size.

So please add "VND.API+JSON" to the const array "_CONTENTAPP".

If you agree, I can create a PR

**Comment by synopse** [comment]
Thanks for the pull request.

It is merged now. 
:)
