### ISSUE TITLE
Different JsonToObject behavior after mORMot2 upgrade

### ISSUE THREAD

**Issue by AntoineGS** [synopse/mORMot2#207]
I am in the process of migrating some code to mORMot2 and have run into an issue where the JSON serializer in mORMot2 takes the class member definition at face value even when it is an ancestor of the instance.
For example if my property is defined as a TObject even though an instance TMyClass is assigned, it will treat it as a TObject.

I created a simple example here using both versions:
https://github.com/AntoineGS/JsonToObjectExample

If I missed an option somewhere I apologize in advance!

PS: Thanks for the quick turnaround on the other two issues I had opened, greatly appreciated!

**Comment by synopse** [comment]
You are right: the actual class was not taken into account, as it should.

Should be fixed now.

**Comment by AntoineGS** [comment]
Awesome, confirmed fixed!
Also I realized I wrote JsonToObject in the Issue.. while the example was obviously ObjectToJson, my bad.
