### ISSUE TITLE
const STATIC_URI= '.static' is invalid in Windows XP

### ISSUE THREAD

**Issue by daselang** [synopse/mORMot2#208]
For Windows XP,
in mORMot2,
in file mormot.rest.mvc.pas,
STATIC_URI = '.static';
we can't create a dir named .static,error tip shows 'must input file name'.
so we can't publish static files such as js,css...

same issue in mORMot1,
in file mORMotMVC.pas
STATIC_URI = '.static';

But in Windows 10,we can name a dir with '.static'

Can you fix this const STATIC_URI with a new name,delete the '.'?
rename it as STATIC_URI = 'static'?

Maybe it is a breakchange.

**Comment by synopse** [comment]
You can create a folder named `.static` on Windows XP.
I just was able to do it.
So I don't understand your problem.

**Comment by daselang** [comment]
Hi, @synopse 必须键入文件名，means 'must input file name'

**Comment by synopse** [comment]
This is an XP explorer bug.
There is no problem using  `mkdir` on the command line or a pascal program, or a tool like TotalCommander.

**Comment by daselang** [comment]
maybe I could use `TMvcViewsAbstract.ViewStaticFolder := MakePath([params.Folder, 'static'], True);` to change the default static folder  which is as same name as `STATIC_URI= '.static'` to store the js,css files,
and still keep the url path `/**/.static/**` mapping to new static file paths.

**Comment by synopse** [comment]
The easiest is just to create the folder. ;)
