### ISSUE TITLE
Exception "Floating point overflow" in TextToVariant

### ISSUE THREAD

**Issue by achechulin** [synopse/mORMot2#214]
When calling TextToVariant with AllowDouble=true I noticed exception "Floating point overflow" In 64-bit Windows build. 32-bit build works without exception.

After some debugging I see the problem is in the following code:

`TextToVariant('1E629839-D230-4EEE-BA04-BE1258EB3AF6', true, v);`

GetNumericVariantFromJson recognizes '1E629839' as a floating point number, and tries to create Double value.

I think we can add more checks to GetNumericVariantFromJson that GUIDs are not recognized as floating point values.

**Comment by synopse** [comment]
Please try with this latest commit above.

**Comment by achechulin** [comment]
Thank's!

But for some GUIDs exceptions "Floating point overflow" are still raised.

For example:

```
261E306F-C59B-4BD2-A8DB-B1A7AB7E3FFF
26E307A5-5FFE-4F19-B2AE-D58EFB6C6134
```

That's expected, because 26 * 10^307 > 1.7 x 10^308.

We already count digits in remdigit variable, so we can use it to substract from 308 an 324.
But сalculate fractional digits is somehwat complicated, may be disable overflow/underflow exceptions via MXCSR?

Generated assembler code for last instruction result := result * v64:
```
cvtsi2sd xmm0,qword ptr [rbp+$20]
movsd xmm1,qword ptr [rbp+$48]
mulsd xmm1,xmm0
movsd qword ptr [rbp+$48],xmm1
movsd xmm0,qword ptr [rbp+$48]
```

**Comment by achechulin** [comment]
Thank's again!

Now I cannot see any exception with any type of input.

Notice, there is a little inconcistency (IMHO):
```
TextToVariant('1e-324', true, v) -> varString '1e-324'
TextToVariant('1e308',  true, v) -> varDouble 1.0
```

**Comment by synopse** [comment]
You are right.

Please try https://github.com/synopse/mORMot2/commit/a4ecda7e

**Comment by achechulin** [comment]
Works fine, I cannot see any exception with any type of input that I was able to guess.
