### ISSUE TITLE
Very high CPU consumption in 2.1.5808

### ISSUE THREAD

**Issue by avavdoshin** [synopse/mORMot2#218]
Hello, Arnaud.

I update mormot from 2.1.5794 to 2.1.5808 for my server app (fpc 3.3.1 / win64) and CPU consumption for server app is 25-30% after any client connected
The same project, but mormot 2.1.5794 - server app CPU consumption is about 3-6%

Can you please check what is broken with update?

**Comment by synopse** [comment]
I am currently fixing this issue.

See https://synopse.info/forum/viewtopic.php?pid=40273#p40273

**Comment by avavdoshin** [comment]
Thank you. I'll be waiting

**Comment by synopse** [comment]
Please try with the latest commit.

https://github.com/synopse/mORMot2/commit/060d5be0
is also critical to include: it avoids a rare - but observed - race condition which could exhaust all working threads of the async server.
Seems pretty stable now.

See https://synopse.info/forum/viewtopic.php?pid=40277#p40277

**Comment by avavdoshin** [comment]
Fixed completely with 2.1.5812. Thank you!
