### ISSUE TITLE
Delphi7: [Fatal Error] mormot.core.data.pas(5801): Internal error: C13081

### ISSUE THREAD

**Issue by Oumlike1** [synopse/mORMot2#222]
Hello
When trying to compile the source code with Delphi 7 I getting this error:
[Fatal Error] mormot.core.data.pas(5738): Internal error: C13081
this error appears in 2 functions: _BC_Ord & _BC_Float

function _BC_Ord(A, B: pointer; Info: PRttiInfo; out Compared: integer): PtrInt;
begin
 // result := RTTI_ORD_COMPARE[Info^.RttiOrd](A, B, Info, Compared);
end;

if i put Result:=..  in comment it works,

Any help or recommendation will be appreciated.
Thanks!

**Comment by synopse** [comment]
I am not able to reproduce the issue with Delphi 7 here.

Compilation works:
```
***** mORMot 2 integration using Delphi 7 for win32 *****
d:\dev\lib2\test
Borland Delphi Version 15.0
Copyright (c) 1983,2002 Borland Software Corporation
538993 lines, 6.48 seconds, 4047988 bytes code, 300769 bytes data.
```
Ensure you have all the updates for Delphi 7.1.
