### ISSUE TITLE
Issue with `JsonToVariantDynArray`

### ISSUE THREAD

**Issue by Freedomax** [synopse/mORMot2#229]
When calling `JsonToVariantDynArray` with the following JSON file, the length of the resulting array is incorrect. The obtained length is **852**, while the actual length is **750**.
[1.txt](https://github.com/synopse/mORMot2/files/13537558/1.txt)

**Comment by synopse** [comment]
Which compiler?

**Comment by synopse** [comment]
Please try with the latest commit.

And reopen if needed.
