### ISSUE TITLE
Windows API Multiple defined symbols

### ISSUE THREAD

**Issue by Coldzer0** [synopse/mORMot2#230]
Hello @synopse 

I was working on my project [ImGui-Pascal](https://github.com/Coldzer0/ImGui-Pascal), and It requires linking with some Windows libraries, one of them is **msvcrt** 
And I was recreating one of my projects to use it as a UI and mORMot2 as the backend.

Now the problem is these APIs are already defined in `src\lib\mormot.lib.static.pas` 
```
Error: Multiple defined symbol "__strtod"
Error: Multiple defined symbol "__imp__localtime64"
```

`__strtod` is only used by `src\lib\mormot.lib.quickjs.pas`, which can be handled with an IFDEF if QuickJS is used.

But the real problem is `imp_localtime64 := @localtime64;` which I assume is used for some other library (not sure).

So, what do you think about this case?

**Comment by synopse** [comment]
Please use the forum to discuss this.

Then ReOpen the issue if needed.
