### ISSUE TITLE
While compiling mormot.db.sql.ibx gives compile error on Delphi 12!

### ISSUE THREAD

**Issue by mozpinar** [synopse/mORMot2#235]
1- [dcc32 Fatal Error] mormot.db.sql.ibx.pas(63): F2613 Unit 'IB' not found. 
Line 63
2-I changed it to IBX.IB, then 
[dcc32 Error] mormot.db.sql.ibx.pas(120): E2010 Incompatible types: 'UTF8String' and 'string'
Line 120
3-I changed type of fFirebirdLibraryPathName to RawUtf8 and then
[dcc32 Error] mormot.db.sql.ibx.pas(145): E2003 Undeclared identifier: 'IFirebirdAPI'
Line 145

Mustafa Ozpinar

**Comment by synopse** [comment]
It uses and requires the IBX library for Lazarus - https://www.mwasoftware.co.uk/fb-pascal-api

So it is NOT and will never be Delphi compatible.

Uses Zeos instead on Delphi.
And it was reported to be much faster than IBX:
https://synopse.info/forum/viewtopic.php?pid=40883#p40883

Anyway, some Pull Requests seems to be on their way, we will wait for them.

**Comment by synopse** [comment]
I guess https://github.com/synopse/mORMot2/pull/236 should have fixed at least part of it.
