### ISSUE TITLE
Compile issue with test/mormot2tests.dproj on current master branch

### ISSUE THREAD

**Issue by BastianTeufel-GTR** [synopse/mORMot2#237]
Hi,

I've followed the instructions in the README file to set mormot2 up on my Delphi (12) installation.
On the final step, when trying to build the mormot2tests project, the following error pops up:

![grafik](https://github.com/synopse/mORMot2/assets/147165712/8ecff3ce-bbf0-42e0-8291-730836458e4f)

There's a typo in the variable name in unit `test.soa.core`, 
Line 1720, Variable `hlrAfter1MB` is not defined -> the var name should be `hrtAfter1MB`

```Pascal
    if withlog then
      HTTPServer.HttpServer.Logger.DefaultRotate := hlrAfter1MB;
```

After adjusting the file accordingly it compiles: 

```Pascal
    if withlog then
      HTTPServer.HttpServer.Logger.DefaultRotate := hrtAfter1MB;
```

**Comment by synopse** [comment]
shoud be fixed now.

thanks for the report. ;)

**Comment by synopse** [comment]
Please close the issue if you think it is resolved. :D

For a first test/overview, it may be a good idea to try from the last release instead of plain trunk, which may be unstable until the nightly automated tests are run. ;)
