### ISSUE TITLE
Circular Reference Issue in Project04InterfaceBasedServer.dproj in martin-doyle's example 04-InterfacedBasedServices

### ISSUE THREAD

**Issue by BastianTeufel-GTR** [synopse/mORMot2#240]
When trying to compile the server component of the 04-InterfacedBasedServices sample of @martin-doyle examples, 
I get the following error:

```Pascal
[dcc32 Fataler Fehler] mormot.core.variants.pas(27): F2047 Zirkuläre Unit-Referenz auf 'mormot.core.base'
```

in English:

```Pascal
[dcc32 Fatal error] mormot.core.variants.pas(27): F2047 Circular unit reference to 'mormot.core.base'
```

compiled on Windows 11, Delphi 12, Win32 / Debug

The client component compiles just fine.

**Comment by synopse** [comment]
I have no Delphi 12 available to reproduce the problem.
But no issue on Delphi 11.2 or earlier...

There are clearly no circular reference between mormot.core.variants and mormot.core.base.
Check the source code itself.
So it sounds like a compiler issue, in your specific setup.

Did you clean all *.dcu in your system?

**Comment by synopse** [comment]
Please use our https://synopse.info/forum to discuss this and get help from others than me.

**Comment by BastianTeufel-GTR** [comment]
I found the problem. It was in how Delphi 12 imports the `dpr` file.
When opening the dpr file for the first time, Delphi 12 generates the `dproj` file.

It automatically adds the `mormot.core`into the projects unit scope.
This leads to the circular reference.

When removing the entry, it compiles as expected.

![grafik](https://github.com/synopse/mORMot2/assets/147165712/91e71940-997e-4769-a2cd-d87d5a718579)
