### ISSUE TITLE
Exported package threadvar CurrentThreadName

### ISSUE THREAD

**Issue by hafedh-trimeche** [synopse/mORMot2#241]
Hi,

Would **CurrentThreadName** be placed inside implementation section and called using a function?

The compiler reported this worning:

`[dcc32 Warning] Controller.dpk(79): W1032 Exported package threadvar 'mormot.core.os.CurrentThreadName' cannot be used outside of this package`

[https://docwiki.embarcadero.com/RADStudio/Alexandria/en/W1032_Exported_package_threadvar_%27%25s.%25s%27_cannot_be_used_outside_of_this_package_(Delphi)](url)

Best regards.

**Comment by synopse** [comment]
Should work as you expect now.

Please reopen if needed.
