### ISSUE TITLE
Would it be of interest to automated tests run on GitHub Actions?

### ISSUE THREAD

**Issue by cclauss** [synopse/mORMot2#245]
I have created automated tests for numerous languages but never for Pascal.  It might be an interesting challenge.

Would it be of interest to have this repo run automated tests when code is changed?
* Like: https://github.com/pyodide/pyodide/actions
* This workflow suggests that it would be possible: https://github.com/exercism/free-pascal/blob/main/.github/workflows/test.yml

The use of GitHub Actions is free of charge for public repos like this one. https://github.com/features/actions

**Comment by synopse** [comment]
The repo is run every night on 25 diverse OS, Intel and ARM, Windows, Linux, MacOS.
https://luti.tranquil.it/history/tis-test-mormot2

It is not on github, but on the build farm of the company I work for.
https://blog.synopse.info/?post/2023/07/20/The-LUTI-and-the-mORMot

**Comment by cclauss** [comment]
On the other repo I got test results: https://github.com/exercism/free-pascal/pull/21/checks?check_run_id=23603820352
