### ISSUE TITLE
Cannot compile in Delphi with a Linux 64 target

### ISSUE THREAD

**Issue by gcarreno** [synopse/mORMot2#246]
Hey Arnaud(@synopse),

While attempting to compile [Georges entry](https://github.com/gcarreno/1brc-ObjectPascal/tree/main/entries/ghatem) for `1BRC` I was unable to do it.

From a very superficial look into it, it appears that `mORMot2`'s `.inc` files make Delphi think that it's on a Windows target. And because of that, a lot of the `{$IFDEF}`s will fail.

This for the latest `mORMot2` v2.2 stable with Delphi 12.1.

I don't quite know how to better describe this issue, sorry Arnaud!!

But I'm completely available to test this and get to the bottom of it.

Many thanks in advance.

Cheers,
Gus

**Comment by synopse** [comment]
mORMot is not compatible with Delphi for Linux: only Delphi for Windows.

I don't have any Delphi for Linux compiler. ;)

**Comment by gcarreno** [comment]
Hey Arnaud(@synopse),

> I don't have any Delphi for Linux compiler, to be honest. :wink: 

I suspected as much, hence me offering to help with getting this to work.

Cheers,
Gus

**Comment by synopse** [comment]
I don't think how I may be able to do it without even a Delphi for Linux compiler on my side.
Honestly, no one asked for this support yet, once they found out FPC + Lazarus on Linux.
I use FPC + Lazarus on Linux since years, as my main dev and work platform.
https://synopse.info/forum/viewtopic.php?pid=36212
https://synopse.info/forum/viewtopic.php?id=5864

And last time someone checked the Delphi for Linux compiler generated code, it was just cr*p.

**Comment by gcarreno** [comment]
To be quite honest, you make a lot of sense.

I guess that I kinda had a knee jerk reaction and came here instead of using my head a bit more.

**Comment by myonlylonely** [comment]
@synopse 
Will Delphi for Linux support still be considered in the roadmap?
Surely we could use FPC for new projects. But a lot of people like me are trying to migrate the old Windows project to Linux, a total rewrite in FPC is often not practical. To be honst, I  have used a lot of 3rd party libraries in my project, but for now mORMot is the last 3rd party library that does not support Delphi for Linux. I have to write a adapter to use mORMot and Indy version of HTTP Server.
