### ISSUE TITLE
sqlite3.o: undefined reference to `fcntl64'

### ISSUE THREAD

**Issue by velissariouc** [synopse/mORMot2#247]
I crosscompile in windows 11 using Lazarus with target aarch64 and I get the following message:

Debug: C:\fpcupdeluxe\cross\bin\aarch64-linux\aarch64-linux-gnu-ld.exe: E:\sw\mORMot2-2.2.stable\src\db\..\..\static\aarch64-linux\sqlite3.o:(.data+0x268): undefined reference to `fcntl64'

Before migrating to mormot2 I tried with mormot and I got the same message.

**Comment by synopse** [comment]
I don't have this issue here.
And aarch64-linux seems fine with nightly builds.
https://luti.tranquil.it/history/tis-test-mormot2

Try with the statics from 
https://synopse.info/files/mormot2static.7z

My guess is that they are correct.
Time for a new release perhaps.

**Comment by velissariouc** [comment]
I used the statics from your link but it didn't work.
I tried also with
https://github.com/synopse/mORMot2/archive/refs/heads/master.zip and it did
not work.

I tried to cross compile from a virtual linux machine but with no luck:
Error: /home/costas/fpcupdeluxe/cross/bin/aarch64-linux/aarch64-linux-ld:
/home/costas/sw/mORMot2-master/src/db/../../static/aarch64-linux/sqlite3.o:(.data+0x268):
undefined reference to `fcntl64'

**Comment by synopse** [comment]
Sounds like a libc library version issue. 
Did you try to cross-compile from Linux x86_64 instead of Windows?
Did you try to download the latest cross-compiler and .o from fpcupdeluxe?

**Comment by synopse** [comment]
No reaction from @velissariouc 

Please use the forum to discuss this issue, and reopen if needed.
