### ISSUE TITLE
THttpServer - Process ClientSock don't capture RemotePort

### ISSUE THREAD

**Issue by FernandoBanhos** [synopse/mORMot2#249]
In the THttpServer.Process procedure when preparing THttpServerRequest (var req), ClientSock.fPort is equal to zero, and consequently it is also not transferred internally to the object

![image](https://github.com/synopse/mORMot2/assets/69670357/080428e2-3462-4389-ac3f-22e4c1e36c0b)

**Comment by synopse** [comment]
Why do you need the client port over HTTP?
It does not make any  common sense, because you don't have access to the socket, so you can 't do anything with this information.
No Web server is providing this information, for a good reason.
Please use the forum to discuss this.
