### ISSUE TITLE
THttpServerRequestAbstract - RemoteIP equals 127.0.0.1

### ISSUE THREAD

**Issue by FernandoBanhos** [synopse/mORMot2#250]
When an external sock client accesses my server, the RemoteIP property of the THttpServerRequestAbstract object is always equal to 127.0.0.1

**Comment by synopse** [comment]
I don't understand what you mean by "external sock client".

Do you mean over a reverse proxy?
It is as expected. You need to set a HTTP header for the proxy.

Please use the forum to discuss this.
