### ISSUE TITLE
error while compiling mormot.core.test from lazarus package if NOEXCEPTIONINTERCEPT is set

### ISSUE THREAD

**Issue by Coldzer0** [synopse/mORMot2#253]
Hello @synopse 

I was testing some code, and I needed to use `NOEXCEPTIONINTERCEPT`, but when I did, the Lazarus package couldn't compile.

Because of this line https://github.com/synopse/mORMot2/blob/282cd74bf0c3d32509c8d529daa849a0a8fead2e/src/core/mormot.core.test.pas#L1355

```
mormot.core.test.pas(1355,38) Error: Identifier not found "GetLastExceptionText"
```

**Comment by synopse** [comment]
It compiles now.
But not tested if 100% working. ;)

**Comment by Coldzer0** [comment]
I tested it, and everything works fine now.
