### ISSUE TITLE
Internal Error: URW1147

### ISSUE THREAD

**Issue by Uefi1** [synopse/mORMot2#255]
Hello in the new version 2.2 when trying to compile on Delphi XE2 error F2084 Internal Error: URW1147 this error occurs in the file mormot.core.json

**Comment by synopse** [comment]
Did you try with the latest trunk revision?

**Comment by Uefi1** [comment]
Oh, sorry, not version 2.2, but the latest one, if downloaded via github>code>download

**Comment by synopse** [comment]
This is a compiler bug, specific to XE2.
I don't have this compiler installed, so I can't fix it. It work on my side with Delphi 2010 and XE4.

**Comment by Uefi1** [comment]
> This is a compiler bug, specific to XE2. I don't have this compiler installed, so I can't fix it. It work on my side with Delphi 2010 and XE4.

You know, I once encountered such a bug, the problem was in the inline directive

**Comment by synopse** [comment]
Yes, I know but without a compiler, I don't know how to circumvent it.

You could try to disable some "inline;" in the source code, perhaps not even in mormot.core.json but in mormot.core.rtti.
Try first to add {$undef HASSAFEINLINE} in the beginning of the unit.

**Comment by Uefi1** [comment]
Damn, there’s something deeper there, I tried as you said, but it didn’t work (I can’t even track this error with a debugger (

**Comment by Uefi1** [comment]
Hi, it looks like the latest release that compiled without this error is https://github.com/synopse/mORMot2/commit/b5465402ba62ec049da25851d70d125feff87259

**Comment by Uefi1** [comment]
Or maybe the binaries do not fit the latest library and that’s why the error occurs?

**Comment by Uefi1** [comment]
Can you somehow fix this ?

**Comment by synopse** [comment]
Without the compiler itself, I can't.

**Comment by Uefi1** [comment]
Try downloading Delphi XE2 ?

**Comment by Uefi1** [comment]
Hello, I actually found the latest version that still compiles on Delphi XE2, this one: 
https://github.com/synopse/mORMot2/commit/0f65917f96cacfcd3cafc1abcd623629b8ffd268

**Comment by synopse** [comment]
What if you change 
`procedure AddU(Value: PtrUInt);`
into
`procedure AddU(Value: cardinal);`
in mormot.core.text ?

**Comment by Uefi1** [comment]
No, unfortunately it didn’t help =(

**Comment by synopse** [comment]
I was able to install a Delphi XE2 compiler.

First of all, I see no problem with Win32 target.
Only on Win64 I got this `F2084 Internal Error: URW1147`.
I will try to investigate. Delphi is just buggy as hell.

**Comment by synopse** [comment]
@Uefi1 
Did you install all available updates on your Delphi XE2? That is UP4+HF1?
https://blog.marcocantu.com/blog/delphi_xe2_hotfix_4_1.html

**Comment by synopse** [comment]
Please try with this above commit.

**Comment by Uefi1** [comment]
> Please try with this above commit.

Yes, this commit compiles successfully, it worked, thank you very much =)

**Comment by Uefi1** [comment]
Hurray, the latest version now compiles if you download it from github>Code>download zip thanks for the correction !
