### ISSUE TITLE
WebSocket Client Is not disconnecting

### ISSUE THREAD

**Issue by Coldzer0** [synopse/mORMot2#260]
I was testing the `THttpClientWebSockets` and I noticed that the client never calls `OnClientDisconnected` or `OnWebSocketsClosed` when I disable the Ethernet manually.

Inside `TWebCrtSocketProcess.CanGetFrame`

https://github.com/synopse/mORMot2/blob/398e794b5beda709026ba60727220b719b80dea4/src/net/mormot.net.ws.core.pas#L3042-L3061

The `pending := fSocket.SockInPending(TimeOut);` return -1

But `fSocket.LastLowSocketError` which calls `WSAGetLastError` is returning 0

**Comment by synopse** [comment]
Hello,
I don't understand the exact issue here...

**Comment by Coldzer0** [comment]
I have a `THttpClientWebSockets` connected to a web socket Server.

And I set the `OnWebSocketsClosed` and `Settings.OnClientDisconnected`

After I disconnected the internet manually `to simulate a disconnection.`

![image](https://github.com/synopse/mORMot2/assets/6647006/7888201f-e7d1-44fd-84a5-ea649407a891)

The client never calls `OnWebSocketsClosed` or `Settings.OnClientDisconnected` because it's now in an `infinite loop`. 

The ProcessLoopStepRecive here calls CanGetFrame with the `@socketerror` param to get any socket errors 
https://github.com/synopse/mORMot2/blob/398e794b5beda709026ba60727220b719b80dea4/src/net/mormot.net.ws.core.pas#L2695

But here it always return 0 for me even that `pending := fSocket.SockInPending(TimeOut);` returns  -1

https://github.com/synopse/mORMot2/blob/398e794b5beda709026ba60727220b719b80dea4/src/net/mormot.net.ws.core.pas#L3053

So `sockerror` never gets an error value, and the ProcessLoop continues forever.

**Comment by Coldzer0** [comment]
Sometimes, the disconnection happens, but sometimes, It gets into that infinite loop

`WSAGetLastError` MS Docs says
```
WSAGetLastError should be called immediately. 
This is necessary because some functions may reset the last extended error code to 0 if they succeed, 
overwriting the extended error code returned by a previously failed function.
```

**Comment by Coldzer0** [comment]
Hello @synopse 

What do you think about this?

**Comment by Coldzer0** [comment]
@synopse 
Did you see the comment explaining the issue https://github.com/synopse/mORMot2/issues/260#issuecomment-2161066089

Please let me know if you need more information because this bug is critical on the client side. 
If the server disconnects and the client doesn't know about it, even if I set a ping timer manually, it's not good because it needs at least 30 seconds to reach the ping code to check if the server is still available.

**Comment by synopse** [comment]
I will investigate.

**Comment by synopse** [comment]
So if I understand well, the whole idea of `LastLowSocketError` was wrong.

It seems that the error handling was not clean in other places - I have rewritten `TWebProcessInFrame.Step` too.

Please look at the two above, and come back here with your feedback and findings.

**Comment by Coldzer0** [comment]
I'm just giving it a test run now, but I'll report back ASAP!

**Comment by Coldzer0** [comment]
@synopse Everything works as expected on my test case.

I'll keep testing, and If there are any other issues, I'll open new ones.
Thanks.
