### ISSUE TITLE
PDF/A validation failed (no OutputIntent for RGB)

### ISSUE THREAD

**Issue by tueddy** [synopse/mORMot2#265]
Hi,

validation of a very simple PDF/A fails in Acrobat preflight and some online validators e.g. https://www.pdf2go.com/validate-pdfa or https://www.pdfforge.org/online/de/pdfa-validieren :

> The validation for file Test.pdf against PDF/A-1B validation profile was not successful, your file broke the following rules:
>    - DeviceRGB may be used only if the file has a PDF/A-1 OutputIntent that uses an RGB colour space 
> 

A minimal reproducable example:

```
procedure TForm2.Button1Click(Sender: TObject);
var
  PdfDocument: TPdfDocumentGDI;
  Bmp: TBitmap;
begin
  PdfDocument:= TPdfDocumentGDI.Create;
  try
    PdfDocument.PDFA:= pdfa1B;
    PdfDocument.AddPage;
    // add drawing
    PdfDocument.VclCanvas.Rectangle(200, 10, 300, 110);
    // add text
    PdfDocument.VclCanvas.TextOut(100, 100, 'PDF/A test');
    // add image
    Bmp:= TBitmap.Create(150, 150);
    try
      Bmp.Canvas.Brush.Color:= clBlue;
      Bmp.Canvas.Ellipse(10, 10, 140, 140);
      PdfDocument.VclCanvas.Draw(100, 200, Bmp);
    finally
      Bmp.Free;
    end;

    PdfDocument.SaveToFile('C:\Temp\Test.pdf');
  finally
    PdfDocument.Free;
  end;
end;
```

Something must be wrong with the generated OutputIntent, the RGB output condition does not seem to be recognized by the validator?

**Comment by synopse** [comment]
I suspect you need a RGB bitmap.

Try to set `Bmp.PixelFormat := pf24bit;`

**Comment by tueddy** [comment]
OK, i have found the error:
The PDF/A OutputIntent cannot be validated because of misspelling here:

https://github.com/synopse/mORMot2/blob/2cf1efb12eaac1fdc6a9f2c9a809c2f0d84457ce/src/ui/mormot.ui.pdf.pas#L7130

It should be `dic.AddItem('S', 'GTS_PDFA1');`,  GTS_PdfA1 -> GTS_PDFA1
After this change PDF/A documents validate successfully, tested with Adobe preflight and other validators.
Can you apply the fix?

**Comment by synopse** [comment]
Should be fine now.

Thanks for the report.
