### ISSUE TITLE
How to add custom XMP metadata

### ISSUE THREAD

**Issue by tueddy** [synopse/mORMot2#268]
Hi Arnaud,

I need to add/modify XMP metadata for creating a valid ZUGFeRD-PDF. Currently don't see a way to access metadata because it is only created when saving. I need to add custom metadata like this:

```
<rdf:Description xmlns:fx="urn:zugferd:pdfa:CrossIndustryDocument:invoice:2p0#"
                       fx:ConformanceLevel="EN 16931"
                       fx:DocumentFileName="zugferd-invoice.xml"
                       fx:DocumentType="INVOICE"
                       fx:Version="1.0"
                       rdf:about=""/>
</rdf:RDF>

```
Is there a way to do this? Like a callback event or a custom metadata property?
Thank's & best regards
Dirk

**Comment by synopse** [comment]
Please try with the above commit.

**Comment by tueddy** [comment]
Seems to work fine, thank you very much!
