### ISSUE TITLE
TSqlDBIbx - reading memo as string does not give the contents

### ISSUE THREAD

**Issue by jokusoftware** [synopse/mORMot2#275]
Hello,
I am testing TSqlDBIbx connection and I have detected that reading a memo content as string does not work. I make a small change (disabling the optimized value reading for UTF-8 encoded VARCHAR columns for blob columns) and it seems to work fine. I am attaching a tiny patch with this change.

Best regards,
Joe

[0001-TSqlDBIbxStatement-reading-a-blob-memo-as-string-giv.patch](https://github.com/user-attachments/files/16431166/0001-TSqlDBIbxStatement-reading-a-blob-memo-as-string-giv.patch)

**Comment by synopse** [comment]
Please try with the above commit.

Thanks for the feedback.

**Comment by jokusoftware** [comment]
It is working fine. Thanks.
