### ISSUE TITLE
TRWLock Access violation when using the ASM version of the code

### ISSUE THREAD

**Issue by Coldzer0** [synopse/mORMot2#284]
Hello @synopse 

I was testing the TRWLock and when I try to use sleep after `WriteLock` an Exception thrown from `ReadOnlyLock`

I'm using FPC Trunk version
```
Free Pascal Compiler version 3.3.1-15213-g780c1f9c49 [2024/08/09] for x86_64
```

Here's the test code
```pascal
program Locks_RnD;
uses
  Classes,
  Sysutils,
  mormot.core.os;

var
  Lock : TRWLock;
  Connected : Boolean = False;

Type

  { TThread_X1 }

  TThread_X1 = class(TThread)
  public
    Procedure Execute(); override;
  end;

  { TThread_X1 }

  procedure TThread_X1.Execute();
  var
    Index : Integer = 0;
  begin
    while (not Terminated) and Connected do
    begin
      try
        Lock.ReadOnlyLock;
        try
          WriteLn('X1 Index = ', Index);
          Index += 1;
        finally
          Lock.ReadOnlyUnLock;
        end;
        Sleep(100);
      except
        on E:Exception do
        begin
          WriteLn('Thread_X1 Error : ', E.Message);
          Break;
        end;
      end;
    end;
    WriteLn('Thread X1 Done');
  end;

Type
  { TThread_X2 }

  TThread_X2 = class(TThread)
  public
    Procedure Execute(); override;
  end;

{ TThread_X2 }

procedure TThread_X2.Execute();
var
  Index : Integer = 0;
begin
  while (not Terminated) and Connected do
  begin
    try
      Lock.ReadOnlyLock;
      try
        WriteLn('X1 Index = ', Index);
        Index += 1;
      finally
        Lock.ReadOnlyUnLock;
      end;
      Sleep(50);
    except
      on E:Exception do
      begin
        WriteLn('Thread_X2 Error : ', E.Message);
        Break;
      end;
    end;
  end;
  WriteLn('Thread X2 Done');
end;

var
  ThreadOne : TThread_X1;
  ThreadTwo : TThread_X2;
  I: Integer;
begin
  Lock.Init;
  Connected := True;

  ThreadOne := TThread_X1.Create(False);
  ThreadTwo := TThread_X2.Create(False);

  while Connected do
  begin
    for I := 0 to Pred(4) do
    begin
      if I = 3 then
      begin
        Lock.WriteLock;
        try
          WriteLn('Waiting for 2 sec to test the lock');
          Sleep(2000); // this make other threads throw an exception. {If I undef "FPC_ASMX64" It works fine}
          Connected := False;
        finally
          Lock.WriteUnLock;
        end;
      end;
      Sleep(1000);
    end;
  end;

  ThreadOne.WaitFor;
  ThreadTwo.WaitFor;

  FreeAndNil(ThreadOne);
  FreeAndNil(ThreadTwo);

  Lock.AssertDone;

  WriteLn('Done');
  ReadLn;
end.
```

For some reason RCX is 0 after the use of Sleep after WriteLock
```
 In file 'mormot.core.os.pas' at line 9816:
@spin:  mov     rax, qword ptr [rcx + TRWLock.Flags]
```

![image](https://github.com/user-attachments/assets/d23814db-30ef-4ceb-a955-3c68dc2cbd50)

**Comment by synopse** [comment]
Very good code to reproduce the problem.
Thanks!

I will look into it.

**Comment by synopse** [comment]
It sounded like a nasty stack alignment issue...

Should be fixed now.
At least, it is stable with my testing on Win64 in both Delphi and FPC.

IMPORTANT DISCLAIMER:
TRWLock is designed for VERY small portions of code, and should never lock more than a few instructions.
Using it with second-like locks is pretty unsafe and would burn a lot of CPU for no benefit.

**Comment by Coldzer0** [comment]
> It sounded like a nasty stack alignment issue...
> 
> Should be fixed now. At least, it is stable with my testing on Win64 in both Delphi and FPC.
> 
> IMPORTANT DISCLAIMER: TRWLock is designed for VERY small portions of code, and should never write-lock more than for a few instructions. Using it with second-like write locks is pretty unsafe and would burn a lot of CPU for no benefit.

This commit [fixed TRWLock.ReadOnlyLock on Win64](https://github.com/synopse/mORMot2/commit/ef6363cba1dc1c5b65dcd18fa88e2dfb9a9f3cc0) fixes the problem 

Thanks for the info; I already know that from your blog and comments on the code, but I was doing some testing to better understand the locks in mORMot2.

Again, thanks for your work, and have a nice day.
