### ISSUE TITLE
JSON Array Bug

### ISSUE THREAD

**Issue by Coldzer0** [synopse/mORMot2#291]
Hello @synopse 

I pulled the latest updates from mormot2, and I was testing this code.

```pascal
function GetJSONListTest(): utf8string;
var
  JS, Item: IDocDict;
  I: integer;
begin
  JS := DocDict();
  JS.I['VER'] := 1;
  JS.A['ML'] := DocList();
  for I := 0 to Pred(Screen.MonitorCount) do
  begin
    Item := DocDict();
    Item.I['ID'] := I;
    Item.I['W'] := 1024;
    Item.I['H'] := 1024;
    JS.A['ML'].Append(Item);
  end;
  Result := utf8string(JS.GetJson());
end;
```

Tested on
- Free Pascal Compiler version 3.3.1-15358-gb40d312521 [2024/08/29] for x86_64
- Embarcadero® RAD Studio 12 Version 29.0.51961.7529 

And both gives me `{"VER":1,"ML":[null,null]}`

This code was working before I pulled the latest updates.
I'll try to see which commit causes this problem.

**Comment by Coldzer0** [comment]
Oh my bad I think I need to use `AppendDoc` not `Append`

**Comment by synopse** [comment]
So please close the issue?

**Comment by Coldzer0** [comment]
> So please close the issue?

Why did Append work before? Was it a logical bug in the code, or what was it?
