### ISSUE TITLE
OpenAPI Multiline description comment bug

### ISSUE THREAD

**Issue by Coldzer0** [synopse/mORMot2#293]
I was testing the new OpenAPI code generator and found out that descriptions with multiline strings are not handled. 
Plus, the names of the Sets are very long.

[apigrpc.swagger.json](https://github.com/user-attachments/files/16852539/apigrpc.swagger.json)

A small example
```JSON
"description": "- UNKNOWN: Unknown environment.\n - SANDBOX: Sandbox/test environment.\n - PRODUCTION: Production environment.",
 ```

**Comment by synopse** [comment]
This is a work in progress.
Please try again later.

**Comment by Coldzer0** [comment]
> This is a work in progress. Please try again later.
> 
> One note: there is no \n nor any set/enum in the supplied .json file.

That's in the "description" string object some of it contains \n and \n\n

**Comment by synopse** [comment]
Please try with the current version.

But I still don't understand what means:

> the names of the Sets are very long.

**Comment by Coldzer0** [comment]
> Please try with the current version.
> 
> But I still don't understand what means:
> 
> > the names of the Sets are very long.
> 
> I suspect the `.json` you provided is not the one you use. There is no enum/set in them. Nor any notion of "Sandbox" in the descriptions. If the sets have no name in the `.json` then a name is computed from the description text, which may indeed be quite long.

The fix for the new line comments is fixed now.
The file is the same, and I think the `OpenAPI: truncate too long generated identifiers` already fixed that.


Another thing about the RegusterRtti that it complains about `_TProtobufAny = '@type:RawUtf8';` 

I don't know how the RegisterCustomEnumValues works, but it didn't like the `@`

![image](https://github.com/user-attachments/assets/ca7995c8-ce15-4a46-8762-48464abbc2fa)

**Comment by synopse** [comment]
Where does this '@' comes from?

It should not exist within our PascalName content.

Please provide a .json to reproduce the issue.
Your previous link has no trouble.

Also ensure you use the very last version of the unit from tonight: I just committed a lot of fixes.

**Comment by Coldzer0** [comment]
> Where does this '@' comes from?
> 
> It should not exist within our PascalName content.
> 
> Please provide a .json to reproduce the issue. Your previous link has no trouble.
> 
> Also ensure you use the very last version of the unit from tonight: I just committed a lot of fixes.
> 
> And one last tip: ensure you specify a aTypeSuffix prefix to TOpenApiParser.Create() otherwise the enumeration and type definitions names may overlap, and the RTTI is lost: this may be the culprit of your "definition covers % bytes" exception.

I do use a prefix, Here's the code I'm using
```Pascal
program mORMot2_RnD;
uses
  mormot.core.fpcx64mm,
  mormot.core.base,
  mormot.net.openapi{, Nakama.dto, Nakama.client};

var
  Nakama : TOpenApiParser;
begin
  Nakama := TOpenApiParser.Create('_NK_');
  try
    Nakama.ParseFile('E:\GameDev\NakamaProject\nakama\apigrpc\apigrpc.swagger.json');
    Nakama.ExportToDirectory('Nakama');
  finally
    FreeAndNilSafe(Nakama);
  end;
  WriteLn('Done');
  ReadLn;
end.
```

It is the same file 

Please Check the `protobufAny` object in the file. 
In its properties, you will see `@type`, which is used in the string used in the RTTI registration.

This problem happens when you put the generated files in the uses and try to run the app.

**Comment by synopse** [comment]
Now I understand.

Please try with the latest commit: it should be fixed now.

**Comment by synopse** [comment]
[nakama.zip](https://github.com/user-attachments/files/16880283/nakama.zip)
Here are the generated files.
They seem correct to me.
