### ISSUE TITLE
Issue in the new implementation of Utf8ToWideChar

### ISSUE THREAD

**Issue by syagrius** [synopse/mORMot2#296]
Hi @synopse,

I think I found an issue in the new implemenation of Utf8ToWideChar.
I use Delphi 12.1, target Win32

I'm using the JSONToDataSet() function and this function fails with the latest revisions of Mormot2.

After tracing the code I've found an Issue:

**Utf8ToWideChar() truncates the destination string.**
The resulting string is shortened by 1 character.

### How to reproduce

```
procedure  TTestCoreBase._Utf8ToWideChar;
var
  dest: array[0..9] of WideChar;
begin
  Utf8ToWideChar(@dest, '1234567890', 10, sizeof(dest));
  check( WideCharToString(Dest)='1234567890')   //<<   Returns '123456789'
end;
```

### Workaround
Note: It seems that this fixes the problem, but I'm not certain about my correction 

In unit mormot.core.unicode.pas 

I replace lines 2870 and 2899:
`      if PtrUInt(@dest[1]) >=  PtrUInt(endDest) then `
with 
`      if PtrUInt(@dest[1]) >  PtrUInt(endDest) then `

**Comment by synopse** [comment]
The documentation states that
`a WideChar(#0) is added at the end (if something is written)`
So your destination should be defined as:
```
var
  dest: array[0..10] of WideChar;
```

For me, it works as expected and defined.
Especially you NEED to follow this requirement:
`enough place must be available in dest buffer (guess is sourceBytes*3+2)`
which was not the case in your code.
