### ISSUE TITLE
E2250 No overload for RegisterCustomSerializers with this Arguments

### ISSUE THREAD

**Issue by sebfischer83** [synopse/mORMot2#299]
Hi,

with the current source I've got this error when trying to compile.

**Comment by synopse** [comment]
Which compiler?
Which line?
Minimal code to reproduce?

**Comment by synopse** [comment]
Please reopen with additional info, or even better start discussion this on the forum.

**Comment by sebfischer83** [comment]
It happens in the mopenapi project, at line 11031 with Embarcadero® Delphi 10 Seattle Version 23.0.21418.4207

**Comment by synopse** [comment]
Line 11031 of which file?
