### ISSUE TITLE
mget and OPENSSL in Windows

### ISSUE THREAD

**Issue by zen010101** [synopse/mORMot2#301]
There is a piece of code at the beginning of mget:
```pascal
// initialize OpenSSL if needed
{$ifdef USE_OPENSSL}
OpenSslInitialize;
{$endif USE_OPENSSL}
```
There is a missing sentence `NewNetTls := @NewOpenSslNetTls;`, otherwise OpenSSL will not be actually loaded and executed. I think the correct version should be like this:

```pascal
// initialize OpenSSL if needed
{$ifdef USE_OPENSSL}
OpenSslInitialize;
NewNetTls := @NewOpenSslNetTls;
{$endif USE_OPENSSL}
```

**Comment by synopse** [comment]
Please use the forum for such discussion.

Which OS are you using?

On Windows, you need to define the FORCE_OPENSSL  conditional in your project.
On POSIX, `NewNetTls` is already set.
