### ISSUE TITLE
WinErrorText message is truncated

### ISSUE THREAD

**Issue by zen010101** [synopse/mORMot2#302]
![image](https://github.com/user-attachments/assets/1ed54632-9408-4a0e-be8a-e763df4f771e)

```
LastError: GET https://z.cn/ raised EWinHttp [winhttp.dll error 2EF1 (操作已被取_)]
```

The complete errer message should be "操作已被取消" , but “操作已被取_”

**Comment by synopse** [comment]
Which compiler do you use?

Could you debug a little and check where it is actually truncated?

Is it in `DoWin32PWideCharToUtf8()` ?

**Comment by synopse** [comment]
Please try with my latest commits.

I guess was before the supplied output buffer size was too small in DoWin32PWideCharToUtf8().

**Comment by zen010101** [comment]
Fixed 👍
