### ISSUE TITLE
Question: Can we divide some of features of mORMot 2 in separate repos?

### ISSUE THREAD

**Issue by EMBBlaster** [synopse/mORMot2#304]
mORMot2 is a great project, but it is also really huge. I've already found some programmers that were intimidated by its size. 
  Also, many times, someone would develop a feature that is already available in mORMot2.
  So, I think we could help the modern Pascal community if we had separate repositories.
  For example, these are some features that I think could live in their own repositories:

- JSON/UTF-8 and RTTI kernel;
- some of 'the reusable bricks' (e.g., cryptography, logging, etc.);
- External libraries (e.g., OpenSSL);
- mORMot core;

I know this would probably cause some work, but IMHO, it could be beneficial in the long term.
Have you ever thought about that?

**Comment by zen010101** [comment]
You may post this on the forum: https://synopse.info/

**Comment by synopse** [comment]
This would be more like a question to ask in the forum.
https://synopse.info

In fact, if you look closer, this is exactly what we did with mORMot 2.
Every unit is already self-contained, or have as few dependency as possible.
Look at the repository: you already have in `src/core` the core units, clearly uncoupled and following the SOLID principles.

You would find:
    JSON: mormot.core.json
    UTF-8: mormot.core.unicode
    RTTI kernel: mormot.core.rtti
    some of 'the reusable bricks' 
       cryptography: mormot.crypt.core and its other folder units
        logging: mormot.core.log
       etc: other mormot.core.*
    External libraries (e.g., OpenSSL): mormot.lib.openssl and mormot.crypt.openssl
    mORMot core: mormot.core.base and mormot.core.os

I don't see any benefit in making several repositories.
The Delphi or FPC compiler is already only linking what is needed.

**Comment by EMBBlaster** [comment]
> You may post this on the forum: https://synopse.info/

Thank you. But really, I don't want to generate a discussion with many users of mORMot about this topic. I'd rather just question here to get a simple answer. If the answer is "we need discuss that in forum", then ok, we can migrate.
I don't wish to waste the time of @synopse because, as I see, he is always kind, but also very busy man. :)

> This would be more like a question to ask in the forum. https://synopse.info

Tried to address this above...
Obs: I have tried to tag/label this issue with question, but couldn't.

> I don't see any benefit in making several repositories. 

The benefit is, that some parts could be used by other projects or frameworks.
For example, and remember this is just an example:
   Imagine that one developer is implementing an game engine (e.g like Castle Engine). And, for some reason, it need a XML and JSON parsers that are can run in FPC/Delphi and more platforms as possible. I will could use the ones implemented in mORMot... but will really he use mORMot? 
In my experience, people ditch the idea because of the size of mORMot. They say something like: "I just need XML parser, I will not add Logging, SOA, DB, ORM as a requisite for a game engine."

That is what I tried to say in the question.

> Think as mORMot not as a stand-alone per-feature toolbox, but as a replacement run time library (RTL) for both Delphi and FPC. In fact, mORMot does only use a few core system units, then reimplemented everything on its way. Trying to make it more "native" e.g. to latest Delphi would break compatibility with the oldest Delphi, or with FPC. For instance, if we used the official Delphi or FPC JSON units, we would be much slower. If we used the TDataSet of Delphi and FPC, the DB layer would also be much slower. mORMot benefits (compatibility, performance, stability, cross-platform, cross-compiler, openness) comes from those choices.

Yes. I admire mORMot2 project. I work in one project that is trying not to break compatibility with oldest Delphi too. It is hard work. So, it was never in my head any effort to be more "native". 

> If we completely uncouple some repositories from one to the other (e.g. a stand-alone OpenSSL high-wrapper), then there will be a lot of redundant code, making it compatible with both FPC and all Delphi revisions will become more complex, and linking with other parts of the framework (e.g. the mORMot native cryptography) would become also more complex.
> 
> If you can show us where we could do better, we are open to any proposition. But look at the current mORMot 2 source code, and its current folders and units scope first. The `README.md` files in each folder try to made easier finding each feature. And in doubt, most people ask in the forum what you are looking for, and there is always someone how replies within a few hours.

 > If we completely uncouple some repositories from one to the other (e.g. a stand-alone OpenSSL high-wrapper), then there will be a lot of redundant code, making it compatible with both FPC and all Delphi revisions will become more complex, and linking with other parts of the framework (e.g. the mORMot native cryptography) would become also more complex.
>
> If you can show us where we could do better, we are open to any proposition. But look at the current mORMot 2 source code, and its current folders and units scope first. The `README.md` files in each folder try to made easier finding each feature. And in doubt, most people ask in the forum what you are looking for, and there is always someone how replies within a few hours.

I said before: I know this would probably cause extra work. But my idea is **not** to uncouple completely a repository in the strict sense. For example, we could have one repository for XML/Json and other parsers together. This one would require the "mORMot Core" repository where the RTL and other base functionalities is implemented.

How this would be handled I think is debatable, and probably better discussed in forum. I'm not sure for example that Git-Submodules is a good idea.

And just to be clear, I'm not saying that mORMot did or is doing something wrong. It is just sad to me that we have so many good devs working with pascal in opensource on same problems, but not together.

**Comment by synopse** [comment]
Please look again at the source code.

> In my experience, people ditch the idea because of the size of mORMot. They say something like: "I just need XML parser, I will not add Logging, SOA, DB, ORM as a requisite for a game engine."

This does not make much sense.
If you use mormot.core.json you don't link either the logging, the SOA, DB or ORM features of mORMot.

It is the same as saying: "I just need the Delphi VCL TButton and TMemo, and I don't need the TRichViewEdit, so I won't use Delphi".

I see a lot of confusion in your statements, and I don't know how to explain it better. Look at the mORMot source code again, and how its units - and even `/src/*` folders - are decoupled!

**Comment by EMBBlaster** [comment]
> Please look again at the source code.
Maybe you think that I never used mORMot or even looked at the sources.
It is sad... but I do understand. I'm a good lurker. :)
For the record, I did. And that's why I think more devs should use it.
It is also one of my motivations to open this issue. The code is so decoupled that could be easy to put it in separate repositories.

> > In my experience, people ditch the idea because of the size of mORMot. They say something like: "I just need XML parser, I will not add Logging, SOA, DB, ORM as a requisite for a game engine."
> 
> This does not make much sense. If you use mormot.core.json you don't link either the logging, the SOA, DB or ORM features of mORMot.
> 
> It is the same as saying: "I just need the Delphi VCL TButton and TMemo, and I don't need the FireDAC DB compnents, so I won't use Delphi".

No... it’s not quite the same thing. I'm talking about separating mORMot into repositories so people could/would use them.
For example, look at the repositories from Grijjy. They have more than one, with each one serving a specific purpose, including one for [core features](https://github.com/grijjy/GrijjyFoundation). 

> I see a lot of confusion in your statements, and I don't know how to explain it better. Look at the mORMot source code again, and how its units - and even `/src/*` folders - are decoupled!

I'm sorry... I don't see any confusion in my statements. But if you can't understand why using more than one repository could be a good thing, then that's probably on me. My bad.
Now, I don't know how to explain it better either.

> BTW mORMot is already used in Castle Game engine, and several other projects, AFAIR.

Not in the sense of this question, and I did not say it wasn't... Sorry if I did not use a good example.
But anyway, I see you point. 
Thanks for your time. 
Kind regards.

**Comment by synopse** [comment]
Perhaps we could continue with more input on https://synopse.info/forum/viewtopic.php?pid=42353#p42353
