### ISSUE TITLE
Error E2065 'memchr' in mormot.db.raw.sqlite3.static.pas with Delphi 12.2 64-bit Compilation

### ISSUE THREAD

**Issue by flydev-fr** [synopse/mORMot2#306]
### Description:
When compiling a 64-bit project with Delphi 12.2 using the latest 2.3.stable static binaries, i get the following error:

`[dcc64 Error] mormot.db.raw.sqlite3.static.pas(1323): E2065 Unsatisfied forward or external declaration: 'memchr'`

This issue does not occur in 32-bit compilation, only in 64-bit compilation.

**Comment by synopse** [comment]
Did you also update the pascal sources?

**Comment by flydev-fr** [comment]
Yes, I removed everything, downloaded new pascal sources and binaries from [release page](https://github.com/synopse/mORMot2/releases/tag/2.3.stable) then compiled mormot2test.

I get the issue on delphi 64-bit compilation only.
- no issue on delphi 32-bit
- no issue with fpc on 32-bit and 64-bit

If I put sqlite 3.44.2 (from mormot v2.2), compilation is ok but I get the expected: warning _Linked version is 3.44.2 whereas the current/expected is 3.46.1_

ps: I just did it again triple check, same issue.

**Comment by flydev-fr** [comment]
I also just tested with dynamic lib on mvc-blog sample; By commenting raw.sqlite3.static and compiling for 64-bit, it's ok.
_(I downloaded precompiled binaries for Windows 64-bit from [sqlite.org](https://www.sqlite.org/download.html))_

```pascal
uses
  ...
    //mormot.db.raw.sqlite3.static,
  ...
  
begin
  sqlite3 := TSqlite3LibraryDynamic.Create('sqlite3.dll');
  ...

```

**Comment by synopse** [comment]
I am sorry, I am not able to easily make commits from where I am, because I don't have the right computer - I am on holidays in Danemark to give some conference sessions about mORMot.

Could you create a Pull Request just moving the CPU32 endif above, as you did?
It seems the right temporary fix.

**Comment by flydev-fr** [comment]
there's no hurry, I was just pointing out the problem :)

(I will create the PR in about 30 minutes, thank!)
