### ISSUE TITLE
TServiceContainerServer.RemoveFakeCallbackOnConnectionClose riase AV exception

### ISSUE THREAD

**Issue by zen010101** [synopse/mORMot2#312]
How to reproduce the issue:

1. Start Project31ChatServer
2. Start two Project31ChatClient instances, with entering 1 and 2 as their respective names, and both clients now have completed registration and can chat normally
3. At this point, just close the window of Project31ChatClient 1, or press Ctrl-C (Note that the order is important, you must close the window registered first. If the registration order is 2,1, then  2 should be closed )
4. Project31ChatServer will throw an exception, and through Call Stack, we can locate the cause of the exception in the following line of code `fake^ = nil`

```
procedure TServiceContainerServer.RemoveFakeCallbackOnConnectionClose(...)
begin
   ...
   if (fake^.fLowLevelConnectionID = aConnectionID) and ...
   ...
```

The solution is also very simple, just add the judgment condition of fake^<>nil.

**Comment by zen010101** [comment]
补充一点：只有在调用 WebSocketsEnable() 时将 Server.DoWSClose 事件函数传入时，才会调用 RemoveFakeCallbackOnConnectionClose，才会产生异常。

```
      HttpServer.WebSocketsEnable(Server,PROJECT31_TRANSMISSION_KEY, false,
      [pboSynLzCompress], nil, Server.DoWSClose).
        SetFullLog; // full verbose logs for this demo
```

**Comment by dkounal** [comment]
I think I have the same problem

**Comment by synopse** [comment]
My concern is that I still don't understand how a nil pointer could appear in the fFakeCallbacks list.
FakeCallbackRemove() does call fFakeCallbacks.Delete(i) so the slot should be removed, not set to nil.
And there are other places where the code could also GPF if one fFakeCallbacks.List[] = nil.

So checking for `fake^ = nil` is clearly not enough for a true fix.

My guess is that fFakeCallbacks.Delete(i) is called by FakeCallbackRemove() which is called by TInterfacedObjectFakeServer.Destroy within the loop, therefore fFakeCallbacks.Count is not correct with our loop.

**Comment by synopse** [comment]
Please try with my above commit.

**Comment by zen010101** [comment]
In fact, these are two bugs. The first one is fake^ which may cause AV exception due to nil. The second is `TChatService.CallbackReleased()` will not be called when the client exits abnormally, and of course `RemoveFakeCallbackOnConnectionClose()` will not be called in the same case. The reason is that there is a bug in the `TRestHttpServer.WebSocketsEnable` code:

```
function TRestHttpServer.WebSocketsEnable(const aWSURI, aWSEncryptionKey: RawUtf8;
  aWSAjax: boolean; aWSBinaryOptions: TWebSocketProtocolBinaryOptions;
  const aOnWSUpgraded: TOnWebSocketProtocolUpgraded;
  const aOnWSClosed: TOnWebSocketProtocolClosed): PWebSocketProcessSettings;
begin
  if not (fUse in HTTP_BIDIR) then
    EHttpServer.RaiseUtf8(
      'Unexpected %.WebSocketsEnable over % - need e.g. WEBSOCKETS_DEFAULT_MODE',
      [self, ToText(fUse)^]);
  result := (fHttpServer as THttpServerSocketGeneric).WebSocketsEnable(
    aWSURI, aWSEncryptionKey, aWSAjax, aWSBinaryOptions);
  if Assigned(aOnWSUpgraded) or
     Assigned(aOnWSClosed) then
    if fHttpServer is TWebSocketAsyncServer then
    begin
      TWebSocketAsyncServer(fHttpServer).OnWebSocketUpgraded := aOnWSUpgraded;
      TWebSocketAsyncServer(fHttpServer).OnWebSocketClose := aOnWSClosed;
      TWebSocketAsyncServer(fHttpServer).OnWebSocketDisconnect := OnWSAsyncClose;
    end
    else if fHttpServer is TWebSocketServer then
    begin
      TWebSocketServer(fHttpServer).OnWebSocketUpgraded := aOnWSUpgraded;
      TWebSocketServer(fHttpServer).OnWebSocketClose := aOnWSClosed;
      TWebSocketServer(fHttpServer).OnWebSocketDisconnect := OnWSSocketClose;
    end;
end;
```

Only if we define `aOnWSUpgraded` or `aOnWSClosed` will we execute `... Server(fHttpServer). OnWebSocketDisconnect := OnWS... Close`；

```
procedure TRestHttpServer.OnWSClose(aConnectionID: TRestConnectionID;
  aConnectionOpaque: pointer);
      ...
      if services <> nil then
        (services as TServiceContainerServer).
          RemoveFakeCallbackOnConnectionClose(aConnectionID, aConnectionOpaque);
      ...
end;
```

At this time, when the client is interrupted normally or abnormally, `OnWSClose()` will be called, and then `TChatService.CallbackReleased()` is called too.

**Comment by zen010101** [comment]
> Please try with my above commit.
[6099b22](https://github.com/synopse/mORMot2/commit/6099b22f8217006a3affce7f18c1333a971a8bc1) commit fixex the bug 1. 

But bug 2 is still there . I hope in TRestHttpServer.WebSocketsEnable, Regardless of whether aONWSUpgraded or aOnWSClosed is passed, at least fHttpServer.OnWebsocketDisconnect must be assigned to the correct OnWSAyncClose/OnWSSocketClose.

**Comment by synopse** [comment]
Could you make a Pull Request adding
```
if ...
  Assigned(OnWSAsyncClose) or
  ...
```

(I am away from home in Dusseldorf for Ekon 28 so I can't easily make the change)

**Comment by zen010101** [comment]
> Thanks a lot for the very detailed feedback.
> 
> Could you make a Pull Request adding
> 
> ```
> if ...
>   Assigned(OnWSAsyncClose) or
>   ...
> ```
> 
> (I am away from home in Dusseldorf for Ekon 28 so I can't easily make the change)

OK
