### ISSUE TITLE
Install Mormot2 failed

### ISSUE THREAD

**Issue by tanto-grs** [synopse/mORMot2#318]
I try to install mormot2 and got this errors
![image](https://github.com/user-attachments/assets/f3286ab3-7a50-453e-9152-d29b87817f9a)

System Windows 11 x64
Lazarus IDE 3.4
FPC 3.2.2

**Comment by synopse** [comment]
I guess you did not follow the setup instructions, and did not download and uncompress the static files archive.

Please use the forum for such problems.
