### ISSUE TITLE
Race condition in THttpAsyncServer raw.pas

### ISSUE THREAD

**Issue by myonlylonely** [synopse/mORMot2#321]
I have some problems with the [techempower-bench](https://github.com/synopse/mORMot2/tree/master/ex/techempower-bench) example.
I think there is a race condition between the DoRequest thread and the thread which execute the callback function. Please check if I am right or wrong.

```pascal
function TRawAsyncServer.asyncdb(ctxt: THttpServerRequest): cardinal;
begin
  with fDbPool.Async.PrepareLocked(WORLD_READ_SQL, {res=}true, ASYNC_OPT) do
  try
    Bind(1, ComputeRandomWorld(Lecuyer));
    ExecuteAsync(ctxt, OnAsyncDb);
  finally
    UnLock;
  end;
  //a task is pushed to queue, which could be executed in another thread,
  //but here the task could be finshed, before 777 status code is set,
  //even if 777 status code is set before the task creation code,
  //there still could be a race condition, because after DoRequest function,
  //there still some code change the values in the ctxt object, 
  //which could cause a race condition with the callback function OnAsyncDb
  result := ctxt.SetAsyncResponse;
end;
```

**Comment by synopse** [comment]
I guess there is a WaitLock() within THttpAsyncServerConnection.AsyncResponse which would ensure that the main DoRequest thread is finished.

But perhaps the flags may indeed not be properly set.
Try with my next commit.

**Comment by synopse** [comment]
1. Concurrent access to the THttpServerRequest could indeed be a problem. But in practice, result fields (ErrorMessage, or SetOutJson) are perfectly fine. Only changing the flags or the status code may be an issue.  This is the reason why there is a `RespStatus` optional flag to the `OnAsyncResponse` event handler. You don't need to change the flags.

2. The lock has a timeout only waiting for the current main connection thread to set its state. So the delay should be almost minimal, and certainly always < 1ms. So this part should be safe.

**Comment by myonlylonely** [comment]
I'm afraid it did happen during testing. These threads are executed on different cores, and it is not the only program running on that core. So it did happen, but like you said, very low chance.
Is that possible we could add another callback that executed after calling OnAsyncResponse, make sure the user defined callback function is also protected by the locks?

**Comment by synopse** [comment]
Please try with my latest commits:
- it should be safer, and reduce the race condition about the flags checks
- there are additional logs (sllWarning level) which would identify such race conditions at runtime

**Comment by myonlylonely** [comment]
Yes, I did tried the latest commit.
That did lower the chance on a fully loaded system, but not completely. 
And it does has the log 'AsyncResponse read lock failed'.

**Comment by myonlylonely** [comment]
function TRawAsyncServer.async(ctxt: THttpServerRequest): cardinal;
begin
  ExecuteAsync(ctxt, OnAsync);
  result := ctxt.SetAsyncResponse;
  //If the Task finished here, after SetAsyncResponse but before the RespondFlag is set, the response will never sent to the client, and the connection is kept waiting until client timeout because of the flag check.
end;

**Comment by synopse** [comment]
I don't think so.
The TryLock should wait for ResponseFlag to be set.

**Comment by myonlylonely** [comment]
Oh, you are right. I'm looking at the old version, which is LTS 2.3. The flag check is moved to the lock protection in the mater branch.

**Comment by myonlylonely** [comment]
I have another question. If client has a timeout setting, which disconnect before the data is sent, the connection object would be freed. The callback function then called with the ctxt pointer which owns some garbage. How should I write safe code in something like this?

**Comment by synopse** [comment]
This should be handled by
```
  if IsDangling or
     (Sender <> fRequest) or
     (fClosed in fFlags) then
    exit;
```

**Comment by myonlylonely** [comment]
How could `IsDangling` function really check for dangling pointers?
It is a raw pointer just like in C++, the memory could be resued for other objects, even read only access `TPollAsyncConnection.fHandle` variable itself could possibly cause an access violation in that case.

**Comment by synopse** [comment]
The connection ID won't be the same with a new connection.
There is a GC of closed connections, so the pointers are not freed instantly, but reused for another connection.
In which case, I have added a fAsyncConnectionID32 field to ensure this is the actual request, not a recycled connection.
And even if it has been released and reused for anything else after 2 seconds of GC, the recycled pointer will also be detected.

**Comment by myonlylonely** [comment]
If the async task process takes 10 seconds(just for example), and the request object is freed.
The pointer to the request object which I saved earlier could point to a memory that could already been allocated for other code, not even by mORMot. In this case, the code access could cause access violation, could pass the check or not, anything could happen.
Actually, there is no way to actually detect a dangling pointer with raw pointer.
And even there is a way to detect danging pointer, I have to write logic(such as setOutJson) before OnAsyncResponse, that skipped your check(which is wrong any way).

**Comment by myonlylonely** [comment]
The following example, Sleep simulate a task that took a long time. and before the task is finshed, the client could disconnect the connection, causing connection recycled, after 2 seconds, the object is freed. Then the callback has a dangling pointer ctxt. If you use FastMM5 and enable FullDebugMode, OnAsyncResponse will throw an access violation for sure. Because FastMM force the recycled memory to be written some garbage flag, cauing the acess violation to be triggered. In real cases, these memory could be allocated by other code, so the crash is more likely to be appeared random.
```pascal
function TServer.asyncdb(ctxt: THttpServerRequest): cardinal;
var
  aTask: ITask;
begin
  aTask := TTask.Create(
    procedure
    begin
      Sleep(10000);
      G_Server.OnAsyncDb(ctxt);
    end);
  aTask.Start;
  Result := ctxt.SetAsyncResponse;
end;

procedure TServer.OnAsyncDb(Context: TObject);
var
  ctxt: THttpServerRequest absolute Context;
begin
  ctxt.OnAsyncResponse(ctxt);
end;
```

**Comment by synopse** [comment]
The new code would detect such issue, and avoid any GPF.
But you are right: the main point is that you could access `ctxt` out of scope for sure in end-user code, before mORMot code itself.
So the GPF would occur before.

**Comment by myonlylonely** [comment]
Actually，if you enabled FastMM5 with FullDebugMode,you will see the access violation also happened inside AsyncResponse with no user code before that. Again, there is no way to detect dangling pointer.

**Comment by myonlylonely** [comment]
Have you seen my example project?

**Comment by synopse** [comment]
I have fully rewritten the asynchronous response process.
It know uses an integer handle (i.e. a 32-bit sequence) and no dangling THttpServerRequest pointers.
See e.g. https://github.com/synopse/mORMot2/commit/964e1bce

Of course, we need to change how the results are stored.
There is a TConnectionAsyncHandle to transmit as integer, instead of the unsafe THttpServerRequest pointer:
https://github.com/synopse/mORMot2/commit/b50ba26c

But I have not fully tested it.
Could you validate it works as expected?

**Comment by synopse** [comment]
No, there is a GC delay here and the instance won't be freed sooner that this process is finished.
So, this is safe.

**Comment by myonlylonely** [comment]
But client could disconnect at any time.
For example, if client disconnect immediatly after it connect, and the DB async task takes more time than the gc time, there is a chance that GC is triggered after the callback function locate the connection object, causing accessing a freed object after that.

**Comment by synopse** [comment]
There are two GC generations to avoid this.

**Comment by synopse** [comment]
Changing fLastOperation immediately won't change anything.
TryLock() is setting the fWasActive flag which would update it in the next IdleEverySecond.
And the KeepAlive feature is something else, and is implemented in DoRequest.

Note that the fLastOperation field has a diverse meaning once the connection is closed.
It is then used as a millisecond field (whereas if not closed fLastOperaiton is a second field) to support the GC generations.
So the GC don't need to "be delayed" anyway.

**Comment by myonlylonely** [comment]
So a safe access to a dangling pointer or not would be depend on the code execution time.

**Comment by synopse** [comment]
Not here, because of the connection lock.

**Comment by synopse** [comment]
Were you able to still reproduce the problem?

If not, perhaps it is time closing this issue.

**Comment by myonlylonely** [comment]
> No, there is a GC delay here and the instance won't be freed sooner that this process is finished. So, this is safe.

"The instance won't be freed sooner than this process is finished", how could this be guaranteed?

**Comment by synopse** [comment]
The safety comes from its own state.
The connection is in "responding" state, so no thread would close it from its own logic (there is no timeout there yet).
Only if the reading/epoll thread detect a broken connection, then it would be marked as closed. But not released.

IMHO the only race condition may appear if the connection is marked as broken between 
`c := pointer(fAsync.ConnectionFind(Connection));`
and
` locked := c.WaitLock({wr=}false, {ms=}100);`
This `c.Waitlock()` would also ensure that the connection is not closed in-between.
This is a single `if c = nil then ...` condition, which would take no time for sure, and is clearly much less than the 200ms of the first generation of the internal GC.

**Comment by myonlylonely** [comment]
But it is exactly what I said. Some logic depends on the execution time.
It might seem very unlikely to happen, but let me give you a real-world example I encountered to show that no matter how small the chance is, it can still happen in a production environment. 
We have 20 game server instances running on a Windows Server machine. 
During the startup, they need to compile some scripts, so the CPU usage is very high, all 16 cores are 100% utilized. After the compilation stage, the CPU goes back to normal, with 20% usage in an idle state. Every game server instance hosts a HTTP server to receive some management commands, such as health check. 
During the startup, we also have a health check process running on another machine to send HTTP requests to these HTTP servers running on the game server instances. 
Normally, these checks are fine, since they don't take a lot of time to execute. But during the startup stage, the health check process has a chance to crash some game servers. The chances are still low, and it's not easy to reproduce. But after we investigated, we found that it is caused by some code that makes these time assumptions in some multithread logic. It seems very unlikely to have issues under normal CPU usage, since there are no system calls involved, just like the code here.
I think we could accept that the server returns a 500 status code under these circumstances, but not a possible crash.

**Comment by synopse** [comment]
So to fix this paranoid-by-indeed-possible issue, I think I will write and use a new `ConnectionFindAndTryLock()` function.
Call TryLock() within the main read/write lock would be 100% thread-safe.

**Comment by myonlylonely** [comment]
It is no related to this issue, but I have a question for the `OneGC` function.
`fLastOperationMS` is `Int64`, and is assigned with `GetTickCount64`, but `lastms` is `Cardinal`.
Wouldn't `lastms` be truncated if the OS is run continuously for 49.7 days?
```pascal
OneGC(fGC1, fGC2, fLastOperationMS, fKeepConnectionInstanceMS);

function OneGC(var gen, dst: TPollAsyncConnections; lastms, oldms: cardinal): PtrInt;
```

**Comment by synopse** [comment]
This is handled by 
```
      if c.fLastOperation > lastms then
        // need to reset time flag after 42 days (32-bit unlikely overflow)
        c.fLastOperation := lastms;
```

**Comment by myonlylonely** [comment]
Thank you for pointing that out. But the comment is not correct. the wrap happens after 49.7 days, not 42 days.

**Comment by synopse** [comment]
Yes, I wrote this from my old memory.  I missed from a week. ;)
Doesn't change anything in the behavior, though...
https://github.com/synopse/mORMot2/commit/85a48620e12a78cd27ed5819f8f70573d9a6fde4

**Comment by synopse** [comment]
Closing due to no reaction.

Please discuss on the forum, reopen or create a new issue on any problem.

**Comment by myonlylonely** [comment]
Wouldn't `CloseConnection` has similar issues we discussed? `c` is unlocked before `CloseConnection` is executed.
```pascal
if c.DoResponse(res) = soClose then
begin
  if acoVerboseLog in fAsync.fOptions then
    fAsync.DoLog(sllTrace, 'final AsyncResponse: closing #%', [Connection], self);
  locked := false;
  c.UnLockFinal({wr=}false); // unlock before close
  fAsync.fClients.CloseConnection(TPollAsyncConnection(c), 'AsyncResponse');
end;
```

**Comment by synopse** [comment]
No because no-one else would access this connection from now on.

**Comment by myonlylonely** [comment]
I'm replying to your deleted response:
> No because no-one else would access this connection from now on.
I can't agree with that. It still has a chance that `c` is freed by GC between `UnLockFinal` and `CloseConnection`, just like the code we discuss eariler.

**Comment by synopse** [comment]
`c` is not in the GC at that time.

**Comment by myonlylonely** [comment]
You can't be sure about that. If I add a `Sleep` to simluate some behaviour(such as CPU all 100% usage) between those 2 lines, I have tested that before `CloseConnection` is executed, `c` is freed by GC.
```pascal
if c.DoResponse(res) = soClose then
begin
  locked := false;
  c.UnLockFinal({wr=}false); // unlock before close
  Sleep(5000);
  fAsync.fClients.CloseConnection(TPollAsyncConnection(c), 'AsyncResponse');
end;
```

**Comment by myonlylonely** [comment]
I cannot reopen the issue. Should we recreate a new issue to discuss this?

**Comment by synopse** [comment]
Better switch to the forum.

**Comment by myonlylonely** [comment]
I never use the forum before. I will create an account later. Could we discuss this on Github for now？
