### ISSUE TITLE
Test suite execution fails in Delphi 7: Access violation

### ISSUE THREAD

**Issue by ptvoinfo** [synopse/mORMot2#323]
I'm trying to make a simple test for my unit, but execution fails with Access Violation in the following place:

  Rtti.RegisterFromText([
    TypeInfo(TSmbiosBios),            _TSmbiosBios,
    TypeInfo(TSmbiosSystem),          _TSmbiosSystem,
^^^^^^^^^
Access violation is here.

It looks, the code does not check the boundaries of in a string.

![img1](https://github.com/user-attachments/assets/eddf5c12-1b86-4589-8b34-a1b63f6e267b)

**Comment by synopse** [comment]
I just run the mORMot 2 regression tests on Delphi 7 with no trouble.
The problem is likely to be somewhere in your code.

Please use the forum for this.
Opening here an issue is only if there is an issue in the framework.
