### ISSUE TITLE
Wrong type definition in C runtime functions

### ISSUE THREAD

**Issue by zedxxx** [synopse/mORMot2#324]
The `size` parameter of the `integer` type must be replaced with the `size_t` (or `NativeUInt`) type in functions: `strncmp`, `memcmp`

https://github.com/synopse/mORMot2/blob/master/src/lib/mormot.lib.static.pas#L82

https://github.com/synopse/mORMot2/blob/master/src/db/mormot.db.raw.sqlite3.static.pas#L475

**Comment by zedxxx** [comment]
Same for `realloc`, `memmove`, `memcpy`, `memset`

https://github.com/synopse/mORMot2/blob/master/src/db/mormot.db.raw.sqlite3.static.pas#L415

**Comment by synopse** [comment]
Did you encounter any problem due to this issue?
From the asm point of view, it makes no difference with values up to 2GB in size.

I will review the code about this.

**Comment by zedxxx** [comment]
I don't have any real problems with this, just noticed it when reading the source code.

**Comment by synopse** [comment]
Hope it is fine now.
Closing.

Please reopen if needed.
