### ISSUE TITLE
lts-2.3 - no declaration of `AfterModify` procedure in `interface` section of `mormot.net.ldap` unit

### ISSUE THREAD

**Issue by paweld** [synopse/mORMot2#326]
No declaration of `AfterModify` procedure in `interface` section of `mormot.net.ldap` unit.
Branch **lts-2.3**

**Comment by synopse** [comment]
Please try with https://github.com/synopse/mORMot2/commit/751d6ed2

I need to include the branch to the daily build.

**Comment by paweld** [comment]
Thanks, but now the `RawUtf8DynArraySame` function is missing - commits: 1042c2c964749ffff9dee98a1e073392bdf8dd7b and c5f7b16a8a6c10e51b42f4db685ea89a4614ebe3

**Comment by synopse** [comment]
Closing due to no reaction.

Please discuss on the forum, reopen or create a new issue on any problem.

**Comment by paweld** [comment]
Thank you very much.
Have a nice day
