### ISSUE TITLE
Issue when compuling D7 project, (possible bug)

### ISSUE THREAD

**Issue by godinhoaugusto** [synopse/mORMot2#327]
I'm getting an error when compiling a D7 project with the current version:

[Error] mormot.db.rad.pas(1104): Incompatible types: 'TTypeKind' and 'TRttiKind'

(mormot.db.rad.pas)
...
{$ifdef HASNOSTATICRTTI} // for Delphi 7/2007: mimics TypeInfo()
const
  _TBCD: TFakeTypeInfo = (
 ->   Kind: rkRecord;
    Name4: 'TBCD';
    RecSize4: SizeOf(TBcd);
    ManagedCount4: 0);
{$endif HASNOSTATICRTTI}
...
(mormot.core.rtti)
...
 {$ifdef HASNOSTATICRTTI}
  /// enough Delphi 7/2007 RTTI fields to mimic TRttiInfo.RecordManagedFields
  TFakeTypeInfo = packed record
//		Kind: TTypeKind;
		Kind: TRttiKind;
    case integer of
      4: (
        Name4: string[4];
        RecSize4: cardinal;
        ManagedCount4: integer);
      5: (
        Name5: string[5];
        RecSize5: cardinal;
...
Should it be changed to tkRecord and typinfo added to uses clause?

Thanks

**Comment by godinhoaugusto** [comment]
Pls ignore

// Kind: TTypeKind;
Kind: TRttiKind;
its
Kind: TTypeKind;

**Comment by synopse** [comment]
Thanks for the report.

Please try with the above commit.

**Comment by godinhoaugusto** [comment]
No problem. :)
Thank you for your support

**Comment by synopse** [comment]
Please close this issue if it works on your side.
