### ISSUE TITLE
Feature request: use wget with a stream.

### ISSUE THREAD

**Issue by LongDirtyAnimAlf** [synopse/mORMot2#43]
Would it be possible to design a wget overload that uses a dedicated stream as target ?
At this moment the Hasher can be defined, but it always creates a filestream.

`partstream := params.Hasher.Create(TFileStream.Create(part, fmCreate));`

I have a dedicated stream myself with some extras that I would like to use.
So, it would be nice if the TFileStream could be replaced by a dedicated stream.

Please note: this is just a feature request !

**Comment by synopse** [comment]
Implemented as THttpClientSocketWGet.OnStreamCreate optional callback.

**Comment by LongDirtyAnimAlf** [comment]
Working.
Thanks !
