### ISSUE TITLE
TDebugFile doesn't work with gtk2 applications

### ISSUE THREAD

**Issue by salvadorbs** [synopse/mORMot2#45]
Hello everyone,

in these days I am upgrading from mORMot 1.18 to mORMot 2. And I wanted to take advantage of the new TSynMapFile (TDebugFile).

I'm using FPC 3.3.2 and Lazarus 2.2.0 RC1. Compiled with debug info (param = '-g -gl -O1').

With this program (https://github.com/salvadorbs/Asuite/blob/mormot2/3p/dbg2mab/dbg2mab.lpr, it's the modified example of mormot1's map2mab), I try to create a TSynMapFile with my application .dbg file and embedded to the executable.

I haven't issues with gtk3, qt5 and win32 widgetsets, but with gtk2, at some point it goes into Access Violation (in **TSynMapFile.Create(FileName, true)** ).

So, I tried with a sample application with gtk2 widgetset ([dbg2mab.zip](https://github.com/synopse/mORMot2/files/6973830/dbg2mab.zip) ). Same issue.

Then I rebuilt FPC 3.3.2 with no debug info and... it works. But why!?

**Comment by synopse** [comment]
Pretty weird.
There should be a simple somewhere in gtk2 which is not properly handled by our parser...
Did you try to generate DWARF2 or DWARF3 format?

Perhaps our forum at synopse.info/forum is a better place for such discussion.

**Comment by salvadorbs** [comment]
>  Did you try to generate DWARF2 or DWARF3 format?

Yes, but always AV. See log [log_gw2.zip](https://github.com/synopse/mORMot2/files/6975839/log_gw2.zip)

Maybe is gtkaspectframe.inc the culprit?

> Perhaps our forum at synopse.info/forum is a better place for such discussion.

If you want, no problem for me.

**Comment by synopse** [comment]
We need to know where in mormot.core.log.pas the AV occurs, i.e. on which line of our parser, and what is the context at that time.

**Comment by synopse** [comment]
No feedback since one month.

Please come back with more information, and re-open the issue.
Our https://synopse.info/forum is perhaps the best way to discuss this.
