### ISSUE TITLE
Feature request: Named pipes

### ISSUE THREAD

**Issue by DanielAndrascik** [synopse/mORMot2#54]
do you plan to add support for Named pipes as mORMot1 ?

**Comment by synopse** [comment]
Not yet, since we don't see any benefit in respects to sockets, in terms of performance, over the loopback. Since they are not usable from a service, I doubt they would be of any practical benefit - apart from some simple samples.

**Comment by synopse** [comment]
Please use our forum for such public discussion.
https://synopse.info/forum/
