### ISSUE TITLE
[dcc32 Error] mormot.crypt.core.asmx86.inc(2796): E1026 File not found: '..\..\static\delphi\sha512-x86.obj'

### ISSUE THREAD

**Issue by cabeloh** [synopse/mORMot2#55]
..\..\static\delphi\sha512-x86.obj

![image](https://user-images.githubusercontent.com/52643/133993387-ea109476-346d-493c-85e8-2f914b5ac4d5.png)

**Comment by synopse** [comment]
This file is supplied with the https://github.com/synopse/mORMot2/releases static binaries.

I guess there may be something wrong with your setup.
Do the regression tests compile?
