### ISSUE TITLE
Problem with TAsyncClient OnRead ( Never Called When Receive Data From Server) 

### ISSUE THREAD

**Issue by Coldzer0** [synopse/mORMot2#62]
Hello @synopse 

This is related to https://synopse.info/forum/viewtopic.php?id=6038

I Created a Client Example that uses the `TAsyncClient` Class but didn't work as expected.
https://gist.github.com/Coldzer0/8c98a02721979abe116c9089791f55e4

The problem is because the `TAsyncClient.Execute` Never release the readpoll lock for the polling threads.

So I Created this sample
https://gist.github.com/Coldzer0/226e0d4ac724e0c511895b4485594e28

It uses `TAsyncConnection` and I uses this code to add the connection to the internal reading poll.

```pascal
    // assign the new connection to the internal reading poll.
    If Clients.Start(aconnection) Then
    Begin
      // release atpReadPoll lock to handle new subscription ASAP
      ThreadPollingWakeup(fClients.PollRead.PollForPendingEvents(0));

      // Send 2MB As Test - we should receive it
      WriteString(aConnection, DupeString('A', 1024*1024*2));
      Result := True;
    End
```

So I think the `TAsyncClient.Execute` needs to be updated to handle such case.

Regards.

**Comment by Coldzer0** [comment]
@synopse 

So After sometime reading the code I've some concern regards the TAsyncClient.

I think this class should serve the Connection as only a Async ThreadPoll for Read & Write.

So the Idea behind the the aClientsCount should change.
My idea is you should be able to add your own Socket Connection to the TPollAsyncSockets and still works fine.

Take my new code here as example
https://gist.github.com/Coldzer0/c91b6e144ac0c3227f884c3b355326ac
This should work fine But the​Fix only works if I add `aClientsCount` bigger than 0 And It should be available .

So What I propose is the next change and everything should work as expected.

```diff
diff --git a/src/net/mormot.net.async.pas b/src/net/mormot.net.async.pas
index d9a500b7..c2480979 100644
--- a/src/net/mormot.net.async.pas
+++ b/src/net/mormot.net.async.pas
@@ -590 +590,2 @@ type
-  protected
+  Protected
+    Function ConnectionCreate(aSocket: TNetSocket; Const aRemoteIp: RawUtf8; out aConnection: TAsyncConnection): Boolean; Override;
@@ -1717,6 +1718 @@ begin
-  if ConnectionCreate(client, {ip=}'', connection) then
-  begin
-    if fThreadReadPoll <> nil then
-      fThreadReadPoll.fEvent.SetEvent // awake reading thread(s)
-  end
-  else
+  if not ConnectionCreate(client, {ip=}'', connection) then
@@ -2284,0 +2281,16 @@ end;
+function TAsyncClient.ConnectionCreate(aSocket: TNetSocket;
+  const aRemoteIp: RawUtf8; out aConnection: TAsyncConnection): Boolean;
+begin
+  if Terminated then
+    result := false
+  else
+  begin
+    aConnection := fConnectionClass.Create(self, aRemoteIp);
+    result := inherited ConnectionAdd(aSocket, aConnection);
+    if Result then
+      If Clients.Start(aconnection) Then
+        if fThreadReadPoll <> nil then
+          fThreadReadPoll.fEvent.SetEvent; // awake reading thread(s)
+  end;
+end;
+
```
Regards.

**Comment by Coldzer0** [comment]
Hello @synopse 

Did you check my comment above ?

**Comment by synopse** [comment]
This changes the default behavior of ConnectionCreate, which creates the connection, but don't add it, nor start it. As its name states.
So your patch breaks the Liskov substitution principle of OOP.

For a new client connection, ConnectionCreate + Clients.Start() should be called explicitly.
I have modified the source so that 
- TAsyncConnections.ThreadClientsConnect can be called to create a new client on need;
- fClients.Start will awake reading thread(s) using the new fClients.OnStart event

**Comment by Coldzer0** [comment]
Thanks @synopse for the update.

I'm not professional when it's about OOP so excuse my lake of knowledge in this area. (Thanks for the explanation)
The last commit fix the problem 
By using `Self.Clients.Start(connection);` After connecting.

Or just set the clients count to what we want.


Thanks.
