### ISSUE TITLE
AfterCreate Being Called 2 times Before and after socket connected

### ISSUE THREAD

**Issue by Coldzer0** [synopse/mORMot2#64]
#### While doing some socket testing I found out that AfterCreate Is Called 2 times when socket is conencted.

Here
https://github.com/synopse/mORMot2/blob/b89c88b587c5efab2b4690e329b6caa808f05f78/src/net/mormot.net.async.pas#L737-L741

And Here
https://github.com/synopse/mORMot2/blob/b89c88b587c5efab2b4690e329b6caa808f05f78/src/net/mormot.net.async.pas#L1804-L1806

#### Taking what written in the documentation of the method
https://github.com/synopse/mORMot2/blob/b89c88b587c5efab2b4690e329b6caa808f05f78/src/net/mormot.net.async.pas#L83-L87

#### I think This one need to be removed
https://github.com/synopse/mORMot2/blob/b89c88b587c5efab2b4690e329b6caa808f05f78/src/net/mormot.net.async.pas#L737-L741

**Comment by synopse** [comment]
Nice catch!

Thanks for the feedback.

**Comment by Coldzer0** [comment]
The Last update fix it.

Thanks.
