### ISSUE TITLE
TRttiInfo.DynArrayItemSize get 0 when no elType is present

### ISSUE THREAD

**Issue by mksjgj** [synopse/mORMot2#82]
function TRttiInfo.DynArrayItemSize: PtrInt;
begin
  if DynArrayItemType(result) = nil then    
    result := 0;   --> this is an error  !!! Item size is independent of elType 
end;

function TRttiInfo.DynArrayItemType(out aDataSize: PtrInt): PRttiInfo;
begin
  with GetTypeData(@self)^ do
  begin
    aDataSize := elSize;
    result := pointer(elType);    //elType is nil if type does not require cleanup
    if result <> nil then
      result := PPointer(result)^;
  end;
end;

**Comment by mksjgj** [comment]
program Project1;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  System.SysUtils,
  mormot.core.rtti;

type
  PSimpleLocator = ^TSimpleLocator;
  TSimpleLocator = packed record
    Id:Int32;
    Pos: Int32;
  end;
  TSimpleLocatorArray = array of TSimpleLocator;

var
  FXLocArrTyp :PRttiInfo;
  sz:Integer;
begin
  FXLocArrTyp := TypeInfo(TSimpleLocatorArray);

  sz := FXLocArrTyp.DynArrayItemSize;
  WriteLn('DynArrayItemSize:  ItemSize is ' + sz.ToString);  //DynArrayItemSize:  ItemSize is 0

  FXLocArrTyp.DynArrayItemType(sz);
  WriteLn('DynArrayItemType:  ItemSize is ' + sz.ToString);  //DynArrayItemType:  ItemSize is 8

  WriteLn('You can see, something is wrong!');
end.

**Comment by synopse** [comment]
I guess you are using Delphi, not FPC?

**Comment by mksjgj** [comment]
yes delphi 10.3.3

**Comment by synopse** [comment]
Should be fixed now.

Thanks for the feedback.
