### ISSUE TITLE
Junk data can be returned for empty ftWideMemo and ftWideString fields in TVirtualDataSet.GetBlobStream.

### ISSUE THREAD

**Issue by meaninglesscharacterstring** [synopse/mORMot2#83]
The code in `TVirtualDataSet.GetBlobStream` for ftWideMemo and ftWideString fields can result in a stream being returned that contains junk data:

```pascal
{$ifdef HASDBFTWIDE}
ftWideMemo,
{$endif HASDBFTWIDE}
ftWideString:
  result := TRawByteStringStream.Create(
    Utf8DecodeToRawUnicode(data, len));
```

if `len` is zero, then `Utf8DecodeToRawUnicode` will take that as a signal to scan for a null terminator in order to determine the length of the string, however, it seems that (when using a `TBinaryDataSet`, at least), the memory pointed to by `data` is not null-terminated, so we can end up with junk in the stream.

**Comment by synopse** [comment]
Should be fixed now.

**Comment by meaninglesscharacterstring** [comment]
Excellent, that's fixed it, thanks!
