### ISSUE TITLE
the declare of table_column_metadata is wrong

### ISSUE THREAD

**Issue by mksjgj** [synopse/mORMot2#84]
the declare of table_column_metadata in mORMot 2 is:    
table_column_metadata: function(DB: TSqlite3DB; zDbName, zTableName,
      zColumnName: PUtf8Char; var pzDataType, pzCollSeq: PUtf8Char;
      var pNotNull, pPrimaryKey, pAutoinc: PInteger): integer; cdecl;

i think:    var pNotNull, pPrimaryKey, pAutoinc: PInteger
should be:   out pNotNull, pPrimaryKey, pAutoinc: Integer, 

i had checked with  System.Sqlite.pas in Delphi 10.3.3

**Comment by synopse** [comment]
I guess it is fine now with the last week commit.
Please reopen on issue.
