### ISSUE TITLE
why cannot run the same SQLite on Linux at the same time

### ISSUE THREAD

**Issue by scutlemon** [synopse/mORMot2#85]
I use Delphi program to open SQLite database with TSQLRestServerDB. Lockingmode: = lmnormal. The compiler runs on Linux. When the second program is opened, an error is reported: esqlite3exception {"errorcode": 26, "sqlite3errorcode": "secnotadb", "message": "error sqlite_notadb (26) [dbopen] using 3.34.1 with ADB = nil"}.

But it is possible to run on windows.

What is the matter? How should it be solved?

**Comment by synopse** [comment]
what does "the compiler runs on Linux" mean?
I don't understand the issue.

Note: such use problems with not clear questions are better asked (and answered) on our forum https://synopse.info/forum

**Comment by scutlemon** [comment]
> what does "the compiler runs on Linux" mean on your context? how do you compile on Linux? FPC? I don't understand the issue.
> 
> Note: such use problems with not clear questions are better asked (and answered) on our forum https://synopse.info/forum

Yes ,  compile by FPC .
such as :  fpc.exe -Tlinux -Px86_64 -MObjFPC -Scghi -Cg -O1 -l -vewnhibq -FiC:\e\SS2\SysDataManager\mymormot\lib\x86_64-linux -FiC:\lazarus32\ccr\mORMot -FiC:\lazarus32\ccr\mORMot\CrossPlatform -FiC:\lazarus32\ccr\mORMot\static\x86_64-linux -FiC:\e\ss\ziliao\synapse40\source\lib -FuC:\lazarus32\ccr\mORMot -FuC:\e\ss\IRSoft\souce\component -FuC:\lazarus32\ccr\mORMot\SQLite3 -FuC:\lazarus32\ccr\mORMot\static\x86_64-linux -FuC:\e\ss\ziliao\synapse40\synalist-code-r209-trunk\synalist-code-r209-trunk -FuC:\e\SS2\SysDataManager\mymormot\jiekou -FuC:\e\SS2\wavpubfunc -FuC:\e\SS2\SysDataManager\mymormot\ -FUC:\e\SS2\SysDataManager\mymormot\lib\x86_64-linux\ -FEC:\e\SS2\SysDataManager\mymormot\ -oC:\e\SS2\SysDataManager\mymormot\blackir blackir.lpr

I had post it  to the forum and topic id is  37131. Thanks.

**Comment by synopse** [comment]
discussion continuing on the forum. thanks :)
