### ISSUE TITLE
mvc-blog: can't to add comment in FB or pg 

### ISSUE THREAD

**Issue by wesov** [synopse/mORMot2#86]
Error adding comments when enabling other databases except SQLite.

**Comment by synopse** [comment]
Do you mean that adding comments in this sample works with SQLite3, but not external DB like FireBird or PostgreSQL?

**Comment by wesov** [comment]
Yes, thank you for reply.

...
20220512 10064853  +  +    mormot.rest.sqlite3.TRestServerDB(01603490).URI POST blog/ArticleComment in=38 B
20220512 10064853  + call  	mormot.rest.sqlite3.TRestServerDB(01603490) ArticleComment id=10000&title=test&comment=test+text.
20220512 10064853  +  +    	mormot.db.sql.postgres.TSqlDBPostgresConnection(0b0b2b30).Connect
20220512 10064857  + DB    		mormot.db.sql.postgres.TSqlDBPostgresConnection(0b0b2b30) Connected to localhost test using C:\mORMot2\ex\mvc-blog\exe\libpq.dll v100020
20220512 10064857  + DB    		mormot.db.sql.postgres.TSqlDBPostgresStatement(0b0daaa0) Prepare 0us SELECT LOCALTIMESTAMP
20220512 10064857  + SQL   		mormot.db.sql.postgres.TSqlDBPostgresStatement(0b0daaa0) ExecutePrepared 184us rows=1 SELECT LOCALTIMESTAMP
20220512 10064857  +  -    	00.073.744
20220512 10071107  + EXC   	ESqlDBPostgres {Message:"TSqlDBPostgresLib PGERRCODE: D5.$j\u000F?, **_ERROR:  column \"rowid\" does not exist\nLINE 1: SELECT RowID FROM Article WHERE RowID=$1 LIMIT 1\n               ^\n",Statement:null} [HttpSrv 8092blog THttpApiSrv] at 01002c00c4 ../../src/db/mormot.db.raw.postgres.pas_**  (297)
20220512 10071107  + SQL   	mormot.db.sql.postgres.TSqlDBPostgresConnection(0b0b2b30) SELECT RowID FROM Article WHERE RowID=null LIMIT 1
20220512 10071107  + EXC   	ESqlDBPostgres {Message:"TSqlDBPostgresLib PGERRCODE: 

**Comment by synopse** [comment]
Please try with latest commits, which fixed MemberExists() on external databases.

**Comment by wesov** [comment]
Thanks a lot.
