### ISSUE TITLE
Is there anyway to change the TWebSocketAsyncServer fConnectionClass ?

### ISSUE THREAD

**Issue by Coldzer0** [synopse/mORMot2#89]
Hello @synopse 

I'm using `TWebSocketAsyncServer`, and I was trying to create my version of `TWebSocketProcess`, so I can save a reference to the connection in my new class for later use,

like having a TForm instance saved in the class.

I have this class.

```pascal
  { TNewConnection }
  TNewConnection = class(TWebSocketAsyncConnection)
  private
    function CloseMainManager(MainManager : TForm): TThreadProcedure;
    function RemoveConnection(Node: PVirtualNode): TThreadProcedure;
    function AddNewConnection(MySelf: TNewConnection): TThreadProcedure;
    procedure BeforeDestroy;
  public
    Socket : TWebSocketProcess;
    Node: PVirtualNode;
    MainManager : TForm;
    CountOfPackets: UInt64;
    RandomGenerator: TRNLRandomGenerator;
    TasksQueue: TQueueThreads; // Shared ThreadPoll For Tasks Exection.
    constructor Create(aOwner: TAsyncConnections; const aRemoteIP: RawUtf8); reintroduce;
    destructor Destroy; override;
  end;
```

So, for example, when a new connection comes, I create a new TMainManager Form and save a reference to it in the MainManager variable.

My main problem is that the class comes from the `TWebSocketProtocolChat.OnInComingFrame` is `TWebSocketProcess` which I can't save a reference to my class into it so I can track which client I show data on the form related to the connection.

And it turns out that the `TWebSocketAsyncServer` will overwrite `fConnectionClass` with `TWebSocketAsyncConnection` https://github.com/synopse/mORMot2/blob/c1d3a08249c052addbc0fdd784da9c6a5addb316/src/net/mormot.net.ws.async.pas#L538-L540

Maybe we can have a Class variable option in the Create constructor or TWebSocketAsyncServer.

Or maybe you can add a Data property as Pointer to the TSynPersistent that TWebSocketProtocol inherits it so it can be used to store data or whatever the coder wants?

All I need is either to control the `fConnectionClass` related to TWebSocketAsyncServer or to have some Data TObject or Pointer variable to save a reference to my class into it.

Thanks.

**Comment by synopse** [comment]
Please try my last commit.
You can now override the constructor, and set the fConnectionClass/fConnectionsClass before calling the inherited function.

**Comment by Coldzer0** [comment]
Yes, the last commit for `TWebSocketAsyncServer.Create` fixes it for me.

Thanks for your great project.
