### ISSUE TITLE
Random Access Violation on SetCurrentThreadName in TWebSocketProcessClientThread.Execute

### ISSUE THREAD

**Issue by Coldzer0** [synopse/mORMot2#93]
Hello @synopse 

I tested the WebSocket client today, and I randomly got an `Access Violation` related to setting the Thread name.

Here's a screenshot from the call stack showing when the problem happens.

![image](https://user-images.githubusercontent.com/6647006/172019625-26c6a934-5921-46f6-bbb0-567e160c8e97.png)

I got the same problem using the `standard memory manager` and `FastMM4-AVX` and `mormot.core.fpcx64mm`

I'm using the latest stable version with fixes.
```
Verbose: Free Pascal Compiler version 3.2.3-616-gbe560dadf8 [2022/04/18] for x86_64
Verbose: Target OS: Win64 for x64
```

Here's How I Use it

```pascal
Function TNewConnection.Connect: THttpClientWebSockets;
Begin
  Self.IsDisconnected := False;
  
  // MyProtocol is created at TNewConnection.Create
  // Socket is a member of TNewConenction Class
  Socket := THttpClientWebSockets.WebSocketsConnect(IP, Port, MyProtocol,nil,'','ws');

  if Socket <> nil then
  begin
    Socket.Settings.OnClientDisconnected := Self.ClientDisconnect;
  end;
  Result := Socket;
End;
```

**Comment by Coldzer0** [comment]
My bad, I was reusing **MyProtocol**, and It was being freed by the **WebSocketsConnect** if the connection failed.
I just needed to recreate the Protocol Object before sending it to **WebSocketsConnect**


```Pascal
Function TNewConnection.Connect: THttpClientWebSockets;
Begin
  Self.IsDisconnected := False;

  Self.MyProtocol := TWebSocketProtocolChat.Create('', 'ws', DoOnInComingFrame); // Create The Protocol Everytime cuz the connection may fail
  Socket := THttpClientWebSockets.WebSocketsConnect(IP, Port, MyProtocol,nil,'','ws');

  if Socket <> nil then
  begin
    Socket.Settings.OnClientDisconnected := Self.ClientDisconnect;
  end
  else
    Self.MyProtocol := nil; // Make Sure it's nil to not to use it again

  Result := Socket;
End; 
```

Why not use FreeAndNilSafe on the protocol inside **WebSocketsConnect** if you will free it anyway?

**Comment by synopse** [comment]
Because there is no need to keep a reference to it, since it will be owned (or freed) by the method:
```
    // - alternatively, you can specify your own custom TWebSocketProtocol
    // instance (owned by this method and immediately released on error)
    function WebSocketsUpgrade(
      const aWebSocketsURI, aWebSocketsEncryptionKey: RawUtf8;
```
